from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

MINI_GAME = Button(area={'zh-CN': (564, 985, 616, 1000)}, color={'zh-CN': (140, 140, 139)}, button={'zh-CN': (564, 985, 616, 1000)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME.png'})
MINI_GAME_BACK = Button(area={'zh-CN': (206, 1124, 230, 1146)}, color={'zh-CN': (172, 172, 172)}, button={'zh-CN': (206, 1124, 230, 1146)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_BACK.png'})
MINI_GAME_BACK_CONFIRM = Button(area={'zh-CN': (507, 789, 555, 812)}, color={'zh-CN': (109, 196, 236)}, button={'zh-CN': (507, 789, 555, 812)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_BACK_CONFIRM.png'})
MINI_GAME_CHECK = Button(area={'zh-CN': (578, 216, 665, 262)}, color={'zh-CN': (185, 102, 28)}, button={'zh-CN': (578, 216, 665, 262)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_CHECK.png'})
MINI_GAME_CLOSE = Button(area={'zh-CN': (632, 181, 672, 222)}, color={'zh-CN': (126, 126, 126)}, button={'zh-CN': (632, 181, 672, 222)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_CLOSE.png'})
MINI_GAME_EXEC_CHECK = Button(area={'zh-CN': (637, 73, 675, 87)}, color={'zh-CN': (239, 208, 163)}, button={'zh-CN': (637, 73, 675, 87)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_EXEC_CHECK.png'})
MINI_GAME_MISSION = Button(area={'zh-CN': (626, 434, 670, 469)}, color={'zh-CN': (158, 135, 122)}, button={'zh-CN': (626, 434, 670, 469)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_MISSION.png'})
MINI_GAME_MISSION_CHECK = Button(area={'zh-CN': (333, 190, 386, 216)}, color={'zh-CN': (152, 152, 152)}, button={'zh-CN': (333, 190, 386, 216)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_MISSION_CHECK.png'})
MINI_GAME_MISSION_CLOSE = Button(area={'zh-CN': (632, 181, 672, 222)}, color={'zh-CN': (126, 126, 126)}, button={'zh-CN': (632, 181, 672, 222)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_MISSION_CLOSE.png'})
MINI_GAME_MISSION_DONE = Button(area={'zh-CN': (292, 1031, 428, 1054)}, color={'zh-CN': (140, 140, 140)}, button={'zh-CN': (292, 1031, 428, 1054)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_MISSION_DONE.png'})
MINI_GAME_MISSION_REWARD = Button(area={'zh-CN': (285, 1029, 435, 1053)}, color={'zh-CN': (255, 166, 92)}, button={'zh-CN': (285, 1029, 435, 1053)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_MISSION_REWARD.png'})
MINI_GAME_OBSTACLE_1 = Button(area={'zh-CN': (253, 882, 296, 904)}, color={'zh-CN': (86, 23, 17)}, button={'zh-CN': (253, 882, 296, 904)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_OBSTACLE_1.png'})
MINI_GAME_OBSTACLE_2 = Button(area={'zh-CN': (302, 848, 342, 872)}, color={'zh-CN': (114, 105, 105)}, button={'zh-CN': (302, 848, 342, 872)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_OBSTACLE_2.png'})
MINI_GAME_OBSTACLE_3 = Button(area={'zh-CN': (273, 879, 289, 897)}, color={'zh-CN': (101, 183, 66)}, button={'zh-CN': (273, 879, 289, 897)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_OBSTACLE_3.png'})
MINI_GAME_REWARD = Button(area={'zh-CN': (306, 732, 413, 751)}, color={'zh-CN': (171, 137, 59)}, button={'zh-CN': (306, 732, 413, 751)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_REWARD.png'})
MINI_GAME_REWARD_DONE = Button(area={'zh-CN': (242, 1078, 351, 1110)}, color={'zh-CN': (133, 133, 133)}, button={'zh-CN': (242, 1078, 351, 1110)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_REWARD_DONE.png'})
MINI_GAME_START = Button(area={'zh-CN': (428, 964, 519, 998)}, color={'zh-CN': (172, 138, 44)}, button={'zh-CN': (428, 964, 519, 998)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_START.png'})
MINI_GAME_START_CONFIRM = Button(area={'zh-CN': (432, 1186, 489, 1212)}, color={'zh-CN': (172, 162, 140)}, button={'zh-CN': (432, 1186, 489, 1212)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_START_CONFIRM.png'})
MINI_GAME_TOUCH = Button(area={'zh-CN': (368, 795, 526, 824)}, color={'zh-CN': (122, 89, 89)}, button={'zh-CN': (368, 795, 526, 824)}, file={'zh-CN': './assets/zh-CN/event_minigame/event_20250904/MINI_GAME_TOUCH.png'})
