from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/event_button_extract.py.
# Don't modify it manually.

MAIN_GOTO_EVENT = Button(area={'cn': (493, 1077, 538, 1104)}, color={'cn': (111, 111, 112)}, button={'cn': (493, 1077, 538, 1104)}, file={'cn': './assets/event/event_20250703l/MAIN_GOTO_EVENT.png'})
