from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

HIGHLIGHTS_LIST = Button(area={'zh-CN': (295, 123, 316, 145)}, color={'zh-CN': (127, 178, 237)}, button={'zh-CN': (295, 123, 316, 145)}, file={'zh-CN': './assets/zh-CN/daemon/HIGHLIGHTS_LIST.png'})
HIGHLIGHTS_LIST_CLOSE = Button(area={'zh-CN': (650, 120, 679, 148)}, color={'zh-CN': (79, 156, 222)}, button={'zh-CN': (650, 120, 679, 148)}, file={'zh-CN': './assets/zh-CN/daemon/HIGHLIGHTS_LIST_CLOSE.png'})
HIGHLIGHTS_LIST_RED = Button(area={'zh-CN': (645, 533, 662, 549)}, color={'zh-CN': (232, 165, 151)}, button={'zh-CN': (645, 533, 662, 549)}, file={'zh-CN': './assets/zh-CN/daemon/HIGHLIGHTS_LIST_RED.png'})
HIGHLIGHTS_LIST_RED_CHECK = Button(area={'zh-CN': (339, 176, 355, 192)}, color={'zh-CN': (235, 163, 149)}, button={'zh-CN': (339, 176, 355, 192)}, file={'zh-CN': './assets/zh-CN/daemon/HIGHLIGHTS_LIST_RED_CHECK.png'})
HIGHLIGHTS_RED = Button(area={'zh-CN': (689, 624, 708, 638)}, color={'zh-CN': (227, 123, 99)}, button={'zh-CN': (689, 624, 708, 638)}, file={'zh-CN': './assets/zh-CN/daemon/HIGHLIGHTS_RED.png'})
MAIN_STORY_MAP_CLOSE = Button(area={'zh-CN': (250, 117, 276, 128)}, color={'zh-CN': (147, 157, 165)}, button={'zh-CN': (250, 117, 276, 128)}, file={'zh-CN': './assets/zh-CN/daemon/MAIN_STORY_MAP_CLOSE.png'})
MAIN_STORY_MARK_IN = Button(area={'zh-CN': (346, 583, 374, 637)}, color={'zh-CN': (162, 164, 164)}, button={'zh-CN': (346, 583, 374, 637)}, file={'zh-CN': './assets/zh-CN/daemon/MAIN_STORY_MARK_IN.png'})
MAIN_STORY_MARK_OUT = Button(area={'zh-CN': (512, 1041, 534, 1090)}, color={'zh-CN': (157, 158, 158)}, button={'zh-CN': (512, 1041, 534, 1090)}, file={'zh-CN': './assets/zh-CN/daemon/MAIN_STORY_MARK_OUT.png'})
MAIN_STORY_NORMAL = Button(area={'zh-CN': (522, 1153, 577, 1163)}, color={'zh-CN': (69, 193, 249)}, button={'zh-CN': (522, 1153, 577, 1163)}, file={'zh-CN': './assets/zh-CN/daemon/MAIN_STORY_NORMAL.png'})
PLAY_HIGHLIGHTS = Button(area={'zh-CN': (467, 690, 518, 715)}, color={'zh-CN': (158, 222, 250)}, button={'zh-CN': (467, 690, 518, 715)}, file={'zh-CN': './assets/zh-CN/daemon/PLAY_HIGHLIGHTS.png'})
