from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

HIGHLIGHTS_LIST = Button(area={'zh-cn': (295, 123, 316, 145)}, color={'zh-cn': (127, 178, 237)}, button={'zh-cn': (295, 123, 316, 145)}, file={'zh-cn': './assets/zh-cn/daemon/HIGHLIGHTS_LIST.png'})
HIGHLIGHTS_LIST_CLOSE = Button(area={'zh-cn': (650, 120, 679, 148)}, color={'zh-cn': (79, 156, 222)}, button={'zh-cn': (650, 120, 679, 148)}, file={'zh-cn': './assets/zh-cn/daemon/HIGHLIGHTS_LIST_CLOSE.png'})
HIGHLIGHTS_LIST_RED = Button(area={'zh-cn': (645, 533, 662, 549)}, color={'zh-cn': (232, 165, 151)}, button={'zh-cn': (645, 533, 662, 549)}, file={'zh-cn': './assets/zh-cn/daemon/HIGHLIGHTS_LIST_RED.png'})
HIGHLIGHTS_LIST_RED_CHECK = Button(area={'zh-cn': (339, 176, 355, 192)}, color={'zh-cn': (235, 163, 149)}, button={'zh-cn': (339, 176, 355, 192)}, file={'zh-cn': './assets/zh-cn/daemon/HIGHLIGHTS_LIST_RED_CHECK.png'})
HIGHLIGHTS_RED = Button(area={'zh-cn': (689, 624, 708, 638)}, color={'zh-cn': (227, 123, 99)}, button={'zh-cn': (689, 624, 708, 638)}, file={'zh-cn': './assets/zh-cn/daemon/HIGHLIGHTS_RED.png'})
PLAY_HIGHLIGHTS = Button(area={'zh-cn': (467, 690, 518, 715)}, color={'zh-cn': (158, 222, 250)}, button={'zh-cn': (467, 690, 518, 715)}, file={'zh-cn': './assets/zh-cn/daemon/PLAY_HIGHLIGHTS.png'})
