from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

FREE_RECRUIT_CHECK = Button(area={'zh-cn': (99, 993, 184, 1013)}, color={'zh-cn': (189, 119, 119)}, button={'zh-cn': (99, 993, 184, 1013)}, file={'zh-cn': './assets/zh-cn/daily_recruit/FREE_RECRUIT_CHECK.png'})
ORDINARY_RECRUIT_CHECK = Button(area={'zh-cn': (356, 33, 391, 59)}, color={'zh-cn': (62, 98, 113)}, button={'zh-cn': (356, 33, 391, 59)}, file={'zh-cn': './assets/zh-cn/daily_recruit/ORDINARY_RECRUIT_CHECK.png'})
RECRUIT_CONFIRM = Button(area={'zh-cn': (187, 1141, 236, 1166)}, color={'zh-cn': (153, 154, 155)}, button={'zh-cn': (187, 1141, 236, 1166)}, file={'zh-cn': './assets/zh-cn/daily_recruit/RECRUIT_CONFIRM.png'})
RECRUIT_SKIP = Button(area={'zh-cn': (602, 21, 687, 44)}, color={'zh-cn': (120, 122, 123)}, button={'zh-cn': (602, 21, 687, 44)}, file={'zh-cn': './assets/zh-cn/daily_recruit/RECRUIT_SKIP.png'})
SOCIAL_POINT_NOT_ENOUGH = Button(area={'zh-cn': (291, 1046, 312, 1062)}, color={'zh-cn': (120, 46, 47)}, button={'zh-cn': (291, 1046, 312, 1062)}, file={'zh-cn': './assets/zh-cn/daily_recruit/SOCIAL_POINT_NOT_ENOUGH.png'})
SOCIAL_RECRUIT = Button(area={'zh-cn': (231, 1036, 261, 1064)}, color={'zh-cn': (193, 96, 149)}, button={'zh-cn': (231, 1036, 261, 1064)}, file={'zh-cn': './assets/zh-cn/daily_recruit/SOCIAL_RECRUIT.png'})
SOCIAL_RECRUIT_CHECK = Button(area={'zh-cn': (357, 33, 386, 60)}, color={'zh-cn': (172, 75, 127)}, button={'zh-cn': (357, 33, 386, 60)}, file={'zh-cn': './assets/zh-cn/daily_recruit/SOCIAL_RECRUIT_CHECK.png'})
SPECIAL_RECRUIT_CHECK = Button(area={'zh-cn': (358, 37, 384, 52)}, color={'zh-cn': (129, 167, 174)}, button={'zh-cn': (358, 37, 384, 52)}, file={'zh-cn': './assets/zh-cn/daily_recruit/SPECIAL_RECRUIT_CHECK.png'})
