from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

FREE_RECRUIT_CHECK = Button(area={'cn': (99, 993, 184, 1013)}, color={'cn': (189, 119, 119)}, button={'cn': (99, 993, 184, 1013)}, file={'cn': './assets/cn/daily_recruit/FREE_RECRUIT_CHECK.png'})
ORDINARY_RECRUIT_CHECK = Button(area={'cn': (356, 33, 391, 59)}, color={'cn': (62, 98, 113)}, button={'cn': (356, 33, 391, 59)}, file={'cn': './assets/cn/daily_recruit/ORDINARY_RECRUIT_CHECK.png'})
RECRUIT_CONFIRM = Button(area={'cn': (187, 1141, 236, 1166)}, color={'cn': (153, 154, 155)}, button={'cn': (187, 1141, 236, 1166)}, file={'cn': './assets/cn/daily_recruit/RECRUIT_CONFIRM.png'})
RECRUIT_SKIP = Button(area={'cn': (602, 21, 687, 44)}, color={'cn': (120, 122, 123)}, button={'cn': (602, 21, 687, 44)}, file={'cn': './assets/cn/daily_recruit/RECRUIT_SKIP.png'})
SOCIAL_POINT_NOT_ENOUGH = Button(area={'cn': (291, 1046, 312, 1062)}, color={'cn': (120, 46, 47)}, button={'cn': (291, 1046, 312, 1062)}, file={'cn': './assets/cn/daily_recruit/SOCIAL_POINT_NOT_ENOUGH.png'})
SOCIAL_RECRUIT = Button(area={'cn': (231, 1036, 261, 1064)}, color={'cn': (193, 96, 149)}, button={'cn': (231, 1036, 261, 1064)}, file={'cn': './assets/cn/daily_recruit/SOCIAL_RECRUIT.png'})
SOCIAL_RECRUIT_CHECK = Button(area={'cn': (357, 33, 386, 60)}, color={'cn': (172, 75, 127)}, button={'cn': (357, 33, 386, 60)}, file={'cn': './assets/cn/daily_recruit/SOCIAL_RECRUIT_CHECK.png'})
SPECIAL_RECRUIT_CHECK = Button(area={'cn': (358, 37, 384, 52)}, color={'cn': (129, 167, 174)}, button={'cn': (358, 37, 384, 52)}, file={'cn': './assets/cn/daily_recruit/SPECIAL_RECRUIT_CHECK.png'})
