from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ANNOUNCEMENT = Button(area={'zh-cn': (631, 111, 675, 152)}, color={'zh-cn': (48, 143, 231)}, button={'zh-cn': (631, 111, 675, 152)}, file={'zh-cn': './assets/zh-cn/handler/ANNOUNCEMENT.png'})
ANNOUNCEMENT_CHECK = Button(area={'zh-cn': (318, 264, 344, 297)}, color={'zh-cn': (155, 197, 245)}, button={'zh-cn': (318, 264, 344, 297)}, file={'zh-cn': './assets/zh-cn/handler/ANNOUNCEMENT_CHECK.png'})
AUTO_CLICK_CHECK = Button(area={'zh-cn': (359, 22, 423, 41)}, color={'zh-cn': (125, 125, 125)}, button={'zh-cn': (359, 22, 423, 41)}, file={'zh-cn': './assets/zh-cn/handler/AUTO_CLICK_CHECK.png'})
CLOSE_DAILY_LOGIN = Button(area={'zh-cn': (492, 1184, 593, 1222)}, color={'zh-cn': (140, 137, 139)}, button={'zh-cn': (492, 1184, 593, 1222)}, file={'zh-cn': './assets/zh-cn/handler/CLOSE_DAILY_LOGIN.png'})
CONFIRM_A = Button(area={'zh-cn': (354, 819, 393, 844)}, color={'zh-cn': (136, 217, 255)}, button={'zh-cn': (354, 819, 393, 844)}, file={'zh-cn': './assets/zh-cn/handler/CONFIRM_A.png'})
CONFIRM_B = Button(area={'zh-cn': (507, 790, 555, 813)}, color={'zh-cn': (110, 197, 241)}, button={'zh-cn': (507, 790, 555, 813)}, file={'zh-cn': './assets/zh-cn/handler/CONFIRM_B.png'})
CONFIRM_C = Button(area={'zh-cn': (334, 1012, 385, 1036)}, color={'zh-cn': (115, 206, 248)}, button={'zh-cn': (334, 1012, 385, 1036)}, file={'zh-cn': './assets/zh-cn/handler/CONFIRM_C.png'})
DOWNLOAD_CHECK = Button(area={'zh-cn': (115, 618, 356, 639)}, color={'zh-cn': (201, 197, 201)}, button={'zh-cn': (115, 618, 356, 639)}, file={'zh-cn': './assets/zh-cn/handler/DOWNLOAD_CHECK.png'})
LEVEL_UP_CHECK = Button(area={'zh-cn': (312, 601, 408, 618)}, color={'zh-cn': (0, 68, 129)}, button={'zh-cn': (312, 601, 408, 618)}, file={'zh-cn': './assets/zh-cn/handler/LEVEL_UP_CHECK.png'})
LOGIN_CHECK = Button(area={'zh-cn': (225, 1047, 496, 1068)}, color={'zh-cn': (58, 58, 57)}, button={'zh-cn': (225, 1047, 496, 1068)}, file={'zh-cn': './assets/zh-cn/handler/LOGIN_CHECK.png'})
LOGIN_CHECK_B = Button(area={'zh-cn': (219, 1042, 501, 1076)}, color={'zh-cn': (59, 59, 57)}, button={'zh-cn': (219, 1042, 501, 1076)}, file={'zh-cn': './assets/zh-cn/handler/LOGIN_CHECK_B.png'})
LOGIN_PAGE_CHECK = Button(area={'zh-cn': (229, 1247, 495, 1259)}, color={'zh-cn': (64, 64, 63)}, button={'zh-cn': (229, 1247, 495, 1259)}, file={'zh-cn': './assets/zh-cn/handler/LOGIN_PAGE_CHECK.png'})
PAID_GIFT_CHECK = Button(area={'zh-cn': (169, 619, 527, 640)}, color={'zh-cn': (35, 136, 134)}, button={'zh-cn': (169, 619, 527, 640)}, file={'zh-cn': './assets/zh-cn/handler/PAID_GIFT_CHECK.png'})
PAID_GIFT_CONFIRM_CHECK = Button(area={'zh-cn': (85, 562, 614, 587)}, color={'zh-cn': (190, 190, 190)}, button={'zh-cn': (85, 562, 614, 587)}, file={'zh-cn': './assets/zh-cn/handler/PAID_GIFT_CONFIRM_CHECK.png'})
POPUP_CHECK = Button(area={'zh-cn': (251, 660, 460, 678)}, color={'zh-cn': (160, 160, 160)}, button={'zh-cn': (251, 660, 460, 678)}, file={'zh-cn': './assets/zh-cn/handler/POPUP_CHECK.png'})
REWARD = Button(area={'zh-cn': (306, 408, 416, 449)}, color={'zh-cn': (153, 154, 153)}, button={'zh-cn': (306, 408, 416, 449)}, file={'zh-cn': './assets/zh-cn/handler/REWARD.png'})
SERVER_CHECK = Button(area={'zh-cn': (297, 298, 422, 321)}, color={'zh-cn': (164, 203, 247)}, button={'zh-cn': (297, 298, 422, 321)}, file={'zh-cn': './assets/zh-cn/handler/SERVER_CHECK.png'})
SHIFTY_SUPPLIES_CHECK = Button(area={'zh-cn': (450, 419, 550, 454)}, color={'zh-cn': (131, 158, 197)}, button={'zh-cn': (450, 419, 550, 454)}, file={'zh-cn': './assets/zh-cn/handler/SHIFTY_SUPPLIES_CHECK.png'})
SHIFTY_SUPPLIES_CLOSE = Button(area={'zh-cn': (645, 114, 669, 139)}, color={'zh-cn': (173, 177, 182)}, button={'zh-cn': (645, 114, 669, 139)}, file={'zh-cn': './assets/zh-cn/handler/SHIFTY_SUPPLIES_CLOSE.png'})
SYSTEM_ERROR_CHECK = Button(area={'zh-cn': (311, 567, 389, 585)}, color={'zh-cn': (151, 151, 151)}, button={'zh-cn': (311, 567, 389, 585)}, file={'zh-cn': './assets/zh-cn/handler/SYSTEM_ERROR_CHECK.png'})
SYSTEM_MAINTENANCE_CHECK = Button(area={'zh-cn': (241, 589, 458, 604)}, color={'zh-cn': (194, 193, 194)}, button={'zh-cn': (241, 589, 458, 604)}, file={'zh-cn': './assets/zh-cn/handler/SYSTEM_MAINTENANCE_CHECK.png'})
