from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_QUICKLY = Button(area={'zh-cn': (496, 1093, 591, 1125)}, color={'zh-cn': (254, 147, 104)}, button={'zh-cn': (496, 1093, 591, 1125)}, file={'zh-cn': './assets/zh-cn/event_daemon/BATTLE_QUICKLY.png'})
FIGHT_2 = Button(area={'zh-cn': (508, 972, 607, 1000)}, color={'zh-cn': (91, 201, 249)}, button={'zh-cn': (508, 972, 607, 1000)}, file={'zh-cn': './assets/zh-cn/event_daemon/FIGHT_2.png'})
SKIP = Button(area={'zh-cn': (616, 22, 671, 41)}, color={'zh-cn': (133, 134, 133)}, button={'zh-cn': (616, 22, 671, 41)}, file={'zh-cn': './assets/zh-cn/event_daemon/SKIP.png'})
