from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CHALLENGE = Button(area={'zh-cn': (333, 1050, 386, 1077)}, color={'zh-cn': (246, 179, 167)}, button={'zh-cn': (333, 1050, 386, 1077)}, file={'zh-cn': './assets/zh-cn/solo_raid/CHALLENGE.png'})
CHALLENGE_CONFIRM = Button(area={'zh-cn': (509, 790, 552, 812)}, color={'zh-cn': (124, 201, 237)}, button={'zh-cn': (509, 790, 552, 812)}, file={'zh-cn': './assets/zh-cn/solo_raid/CHALLENGE_CONFIRM.png'})
CHALLENGE_CONFIRM_CHECK = Button(area={'zh-cn': (282, 675, 388, 692)}, color={'zh-cn': (197, 197, 197)}, button={'zh-cn': (282, 675, 388, 692)}, file={'zh-cn': './assets/zh-cn/solo_raid/CHALLENGE_CONFIRM_CHECK.png'})
CHALLENGE_QUICKLY_CONFIRM = Button(area={'zh-cn': (418, 977, 511, 998)}, color={'zh-cn': (115, 208, 248)}, button={'zh-cn': (418, 977, 511, 998)}, file={'zh-cn': './assets/zh-cn/solo_raid/CHALLENGE_QUICKLY_CONFIRM.png'})
CHALLENGE_QUICKLY_DISABLE = Button(area={'zh-cn': (502, 973, 583, 994)}, color={'zh-cn': (120, 119, 119)}, button={'zh-cn': (502, 973, 583, 994)}, file={'zh-cn': './assets/zh-cn/solo_raid/CHALLENGE_QUICKLY_DISABLE.png'})
CHALLENGE_QUICKLY_ENABLE = Button(area={'zh-cn': (501, 973, 586, 994)}, color={'zh-cn': (250, 171, 139)}, button={'zh-cn': (501, 973, 586, 994)}, file={'zh-cn': './assets/zh-cn/solo_raid/CHALLENGE_QUICKLY_ENABLE.png'})
ENEMY_DEFEATED = Button(area={'zh-cn': (257, 387, 474, 429)}, color={'zh-cn': (138, 140, 140)}, button={'zh-cn': (257, 387, 474, 429)}, file={'zh-cn': './assets/zh-cn/solo_raid/ENEMY_DEFEATED.png'})
ENEMY_DEFEATED_CONFIRM = Button(area={'zh-cn': (264, 842, 291, 864)}, color={'zh-cn': (75, 193, 246)}, button={'zh-cn': (264, 842, 291, 864)}, file={'zh-cn': './assets/zh-cn/solo_raid/ENEMY_DEFEATED_CONFIRM.png'})
ENTER_FIGHT = Button(area={'zh-cn': (494, 1078, 598, 1103)}, color={'zh-cn': (244, 143, 127)}, button={'zh-cn': (494, 1078, 598, 1103)}, file={'zh-cn': './assets/zh-cn/solo_raid/ENTER_FIGHT.png'})
FIGHT_HISTORY = Button(area={'zh-cn': (599, 786, 661, 801)}, color={'zh-cn': (175, 174, 174)}, button={'zh-cn': (599, 786, 661, 801)}, file={'zh-cn': './assets/zh-cn/solo_raid/FIGHT_HISTORY.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'zh-cn': (266, 1130, 454, 1158)}, color={'zh-cn': (105, 91, 62)}, button={'zh-cn': (266, 1130, 454, 1158)}, file={'zh-cn': './assets/zh-cn/solo_raid/FREE_OPPORTUNITY_CHECK.png'})
RAID_RESULT = Button(area={'zh-cn': (288, 347, 441, 388)}, color={'zh-cn': (141, 143, 143)}, button={'zh-cn': (288, 347, 441, 388)}, file={'zh-cn': './assets/zh-cn/solo_raid/RAID_RESULT.png'})
SOLO_RAID = Button(area={'zh-cn': (42, 586, 84, 608)}, color={'zh-cn': (156, 99, 37)}, button={'zh-cn': (42, 586, 84, 608)}, file={'zh-cn': './assets/zh-cn/solo_raid/SOLO_RAID.png'})
SOLO_RAID_CHECK = Button(area={'zh-cn': (230, 555, 337, 573)}, color={'zh-cn': (139, 106, 34)}, button={'zh-cn': (230, 555, 337, 573)}, file={'zh-cn': './assets/zh-cn/solo_raid/SOLO_RAID_CHECK.png'})
STAGE_CHALLENGE = Button(area={'zh-cn': (348, 491, 370, 517)}, color={'zh-cn': (211, 148, 11)}, button={'zh-cn': (348, 491, 370, 517)}, file={'zh-cn': './assets/zh-cn/solo_raid/STAGE_CHALLENGE.png'})
STAGE_SEVEN = Button(area={'zh-cn': (339, 492, 380, 519)}, color={'zh-cn': (177, 120, 9)}, button={'zh-cn': (339, 492, 380, 519)}, file={'zh-cn': './assets/zh-cn/solo_raid/STAGE_SEVEN.png'})
STAGE_SEVEN_SWITCH = Button(area={'zh-cn': (553, 131, 580, 148)}, color={'zh-cn': (159, 127, 13)}, button={'zh-cn': (553, 131, 580, 148)}, file={'zh-cn': './assets/zh-cn/solo_raid/STAGE_SEVEN_SWITCH.png'})
