from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CHALLENGE = Button(area={'cn': (333, 1050, 386, 1077)}, color={'cn': (246, 179, 167)}, button={'cn': (333, 1050, 386, 1077)}, file={'cn': './assets/cn/solo_raid/CHALLENGE.png'})
CHALLENGE_CONFIRM = Button(area={'cn': (509, 790, 552, 812)}, color={'cn': (124, 201, 237)}, button={'cn': (509, 790, 552, 812)}, file={'cn': './assets/cn/solo_raid/CHALLENGE_CONFIRM.png'})
CHALLENGE_CONFIRM_CHECK = Button(area={'cn': (282, 675, 388, 692)}, color={'cn': (197, 197, 197)}, button={'cn': (282, 675, 388, 692)}, file={'cn': './assets/cn/solo_raid/CHALLENGE_CONFIRM_CHECK.png'})
CHALLENGE_QUICKLY_CONFIRM = Button(area={'cn': (418, 977, 511, 998)}, color={'cn': (115, 208, 248)}, button={'cn': (418, 977, 511, 998)}, file={'cn': './assets/cn/solo_raid/CHALLENGE_QUICKLY_CONFIRM.png'})
CHALLENGE_QUICKLY_DISABLE = Button(area={'cn': (502, 973, 583, 994)}, color={'cn': (120, 119, 119)}, button={'cn': (502, 973, 583, 994)}, file={'cn': './assets/cn/solo_raid/CHALLENGE_QUICKLY_DISABLE.png'})
CHALLENGE_QUICKLY_ENABLE = Button(area={'cn': (501, 973, 586, 994)}, color={'cn': (250, 171, 139)}, button={'cn': (501, 973, 586, 994)}, file={'cn': './assets/cn/solo_raid/CHALLENGE_QUICKLY_ENABLE.png'})
ENEMY_DEFEATED = Button(area={'cn': (257, 387, 474, 429)}, color={'cn': (138, 140, 140)}, button={'cn': (257, 387, 474, 429)}, file={'cn': './assets/cn/solo_raid/ENEMY_DEFEATED.png'})
ENEMY_DEFEATED_CONFIRM = Button(area={'cn': (264, 842, 291, 864)}, color={'cn': (75, 193, 246)}, button={'cn': (264, 842, 291, 864)}, file={'cn': './assets/cn/solo_raid/ENEMY_DEFEATED_CONFIRM.png'})
ENTER_FIGHT = Button(area={'cn': (494, 1078, 598, 1103)}, color={'cn': (244, 143, 127)}, button={'cn': (494, 1078, 598, 1103)}, file={'cn': './assets/cn/solo_raid/ENTER_FIGHT.png'})
FIGHT_HISTORY = Button(area={'cn': (599, 786, 661, 801)}, color={'cn': (175, 174, 174)}, button={'cn': (599, 786, 661, 801)}, file={'cn': './assets/cn/solo_raid/FIGHT_HISTORY.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'cn': (398, 1134, 416, 1154)}, color={'cn': (125, 115, 73)}, button={'cn': (398, 1134, 416, 1154)}, file={'cn': './assets/cn/solo_raid/FREE_OPPORTUNITY_CHECK.png'})
SOLO_RAID = Button(area={'cn': (42, 586, 84, 608)}, color={'cn': (156, 99, 37)}, button={'cn': (42, 586, 84, 608)}, file={'cn': './assets/cn/solo_raid/SOLO_RAID.png'})
SOLO_RAID_CHECK = Button(area={'cn': (230, 555, 337, 573)}, color={'cn': (139, 106, 34)}, button={'cn': (230, 555, 337, 573)}, file={'cn': './assets/cn/solo_raid/SOLO_RAID_CHECK.png'})
STAGE_CHALLENGE = Button(area={'cn': (348, 491, 370, 517)}, color={'cn': (211, 148, 11)}, button={'cn': (348, 491, 370, 517)}, file={'cn': './assets/cn/solo_raid/STAGE_CHALLENGE.png'})
STAGE_SEVEN = Button(area={'cn': (339, 492, 380, 519)}, color={'cn': (177, 120, 9)}, button={'cn': (339, 492, 380, 519)}, file={'cn': './assets/cn/solo_raid/STAGE_SEVEN.png'})
STAGE_SEVEN_SWITCH = Button(area={'cn': (553, 131, 580, 148)}, color={'cn': (159, 127, 13)}, button={'cn': (553, 131, 580, 148)}, file={'cn': './assets/cn/solo_raid/STAGE_SEVEN_SWITCH.png'})
