from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/event_button_extract.py.
# Don't modify it manually.

CHALLENGE = Button(area={'zh-cn': (108, 1002, 136, 1022)}, color={'zh-cn': (164, 156, 150)}, button={'zh-cn': (108, 1002, 136, 1022)}, file={'zh-cn': './assets/event/event_20251016/CHALLENGE.png'})
EVENT_CHECK = Button(area={'zh-cn': (451, 885, 518, 910)}, color={'zh-cn': (151, 112, 102)}, button={'zh-cn': (451, 885, 518, 910)}, file={'zh-cn': './assets/event/event_20251016/EVENT_CHECK.png'})
MAIN_GOTO_EVENT = Button(area={'zh-cn': (470, 1047, 504, 1071)}, color={'zh-cn': (140, 113, 118)}, button={'zh-cn': (470, 1047, 504, 1071)}, file={'zh-cn': './assets/event/event_20251016/MAIN_GOTO_EVENT.png'})
RECEIVE = Button(area={'zh-cn': (297, 811, 423, 832)}, color={'zh-cn': (58, 59, 61)}, button={'zh-cn': (297, 811, 423, 832)}, file={'zh-cn': './assets/event/event_20251016/RECEIVE.png'})
REWARD = Button(area={'zh-cn': (453, 998, 481, 1025)}, color={'zh-cn': (89, 85, 82)}, button={'zh-cn': (453, 998, 481, 1025)}, file={'zh-cn': './assets/event/event_20251016/REWARD.png'})
REWARD_CHECK = Button(area={'zh-cn': (257, 109, 314, 129)}, color={'zh-cn': (140, 95, 92)}, button={'zh-cn': (257, 109, 314, 129)}, file={'zh-cn': './assets/event/event_20251016/REWARD_CHECK.png'})
REWARD_CLOSED = Button(area={'zh-cn': (647, 67, 673, 94)}, color={'zh-cn': (115, 110, 108)}, button={'zh-cn': (647, 67, 673, 94)}, file={'zh-cn': './assets/event/event_20251016/REWARD_CLOSED.png'})
REWARD_RECEIVE = Button(area={'zh-cn': (504, 1135, 651, 1148)}, color={'zh-cn': (195, 120, 121)}, button={'zh-cn': (504, 1135, 651, 1148)}, file={'zh-cn': './assets/event/event_20251016/REWARD_RECEIVE.png'})
REWARD_RECEIVE_DONE = Button(area={'zh-cn': (507, 1136, 645, 1149)}, color={'zh-cn': (175, 165, 155)}, button={'zh-cn': (507, 1136, 645, 1149)}, file={'zh-cn': './assets/event/event_20251016/REWARD_RECEIVE_DONE.png'})
SHOP = Button(area={'zh-cn': (104, 1098, 136, 1126)}, color={'zh-cn': (114, 109, 105)}, button={'zh-cn': (104, 1098, 136, 1126)}, file={'zh-cn': './assets/event/event_20251016/SHOP.png'})
SHOP_ITEM_LOAD_CHECK = Button(area={'zh-cn': (578, 1030, 603, 1052)}, color={'zh-cn': (77, 86, 69)}, button={'zh-cn': (578, 1030, 603, 1052)}, file={'zh-cn': './assets/event/event_20251016/SHOP_ITEM_LOAD_CHECK.png'})
SKIP = Button(area={'zh-cn': (616, 22, 671, 41)}, color={'zh-cn': (133, 134, 133)}, button={'zh-cn': (616, 22, 671, 41)}, file={'zh-cn': './assets/event/event_20251016/SKIP.png'})
STORY_1_CHECK = Button(area={'zh-cn': (451, 885, 518, 910)}, color={'zh-cn': (151, 112, 102)}, button={'zh-cn': (451, 885, 518, 910)}, file={'zh-cn': './assets/event/event_20251016/STORY_1_CHECK.png'})
STORY_1_HARD = Button(area={'zh-cn': (615, 1160, 665, 1233)}, color={'zh-cn': (158, 81, 127)}, button={'zh-cn': (615, 1160, 665, 1233)}, file={'zh-cn': './assets/event/event_20251016/STORY_1_HARD.png'})
STORY_1_HARD_HIDDEN = Button(area={'zh-cn': (612, 1157, 666, 1238)}, color={'zh-cn': (50, 52, 52)}, button={'zh-cn': (612, 1157, 666, 1238)}, file={'zh-cn': './assets/event/event_20251016/STORY_1_HARD_HIDDEN.png'})
STORY_1_HARD_LOCKED = Button(area={'zh-cn': (614, 1151, 651, 1170)}, color={'zh-cn': (104, 106, 111)}, button={'zh-cn': (614, 1151, 651, 1170)}, file={'zh-cn': './assets/event/event_20251016/STORY_1_HARD_LOCKED.png'})
STORY_1_HARD_STAGE_11 = Button(area={'zh-cn': (146, 785, 375, 819)}, color={'zh-cn': (90, 93, 102)}, button={'zh-cn': (146, 785, 375, 819)}, file={'zh-cn': './assets/event/event_20251016/STORY_1_HARD_STAGE_11.png'})
STORY_1_HARD_UNLOCK = Button(area={'zh-cn': (343, 733, 438, 753)}, color={'zh-cn': (157, 161, 163)}, button={'zh-cn': (343, 733, 438, 753)}, file={'zh-cn': './assets/event/event_20251016/STORY_1_HARD_UNLOCK.png'})
STORY_1_NORMAL = Button(area={'zh-cn': (411, 1176, 483, 1201)}, color={'zh-cn': (92, 83, 74)}, button={'zh-cn': (411, 1176, 483, 1201)}, file={'zh-cn': './assets/event/event_20251016/STORY_1_NORMAL.png'})
STORY_1_NORMAL_STAGE_11 = Button(area={'zh-cn': (193, 887, 377, 912)}, color={'zh-cn': (111, 90, 98)}, button={'zh-cn': (193, 887, 377, 912)}, file={'zh-cn': './assets/event/event_20251016/STORY_1_NORMAL_STAGE_11.png'})
STORY_2_HARD_STAGE_11 = Button(area={'zh-cn': (404, 588, 439, 664)}, color={'zh-cn': (150, 150, 149)}, button={'zh-cn': (404, 588, 439, 664)}, file={'zh-cn': './assets/event/event_20251016/STORY_2_HARD_STAGE_11.png'})
STORY_2_NORMAL_STAGE_11 = Button(area={'zh-cn': (317, 746, 404, 788)}, color={'zh-cn': (85, 117, 141)}, button={'zh-cn': (317, 746, 404, 788)}, file={'zh-cn': './assets/event/event_20251016/STORY_2_NORMAL_STAGE_11.png'})
STORY_STAGE_CHECK = Button(area={'zh-cn': (138, 860, 234, 882)}, color={'zh-cn': (177, 177, 177)}, button={'zh-cn': (138, 860, 234, 882)}, file={'zh-cn': './assets/event/event_20251016/STORY_STAGE_CHECK.png'})
TEMPLATE_SHOP_MONEY = Template(file={'zh-cn': './assets/event/event_20251016/TEMPLATE_SHOP_MONEY.png'})
