from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ABNORMAL_INTERCEPTION_CHECK = Button(area={'zh-cn': (95, 854, 256, 880)}, color={'zh-cn': (91, 92, 92)}, button={'zh-cn': (95, 854, 256, 880)}, file={'zh-cn': './assets/zh-cn/interception/ABNORMAL_INTERCEPTION_CHECK.png'})
BATTLE = Button(area={'zh-cn': (466, 1150, 601, 1189)}, color={'zh-cn': (244, 106, 86)}, button={'zh-cn': (466, 1150, 601, 1189)}, file={'zh-cn': './assets/zh-cn/interception/BATTLE.png'})
BATTLE_QUICKLY = Button(area={'zh-cn': (505, 1077, 603, 1106)}, color={'zh-cn': (254, 154, 113)}, button={'zh-cn': (505, 1077, 603, 1106)}, file={'zh-cn': './assets/zh-cn/interception/BATTLE_QUICKLY.png'})
KRAKEN = Button(area={'zh-cn': (314, 299, 696, 1252)}, color={'zh-cn': (5, 3, 3)}, button={'zh-cn': (314, 299, 696, 1252)}, file={'zh-cn': './assets/zh-cn/interception/KRAKEN.png'})
KRAKEN_CHECK = Button(area={'zh-cn': (291, 939, 428, 986)}, color={'zh-cn': (136, 135, 133)}, button={'zh-cn': (291, 939, 428, 986)}, file={'zh-cn': './assets/zh-cn/interception/KRAKEN_CHECK.png'})
TEMPLATE_RED_CIRCLE = Template(file={'zh-cn': './assets/zh-cn/interception/TEMPLATE_RED_CIRCLE.png'})
TRAIN = Button(area={'zh-cn': (226, 666, 339, 698)}, color={'zh-cn': (162, 162, 161)}, button={'zh-cn': (226, 666, 339, 698)}, file={'zh-cn': './assets/zh-cn/interception/TRAIN.png'})
