from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ABNORMAL_INTERCEPTION_CHECK = Button(area={'zh-cn': (95, 854, 256, 880)}, color={'zh-cn': (91, 92, 92)}, button={'zh-cn': (95, 854, 256, 880)}, file={'zh-cn': './assets/zh-cn/interception/ABNORMAL_INTERCEPTION_CHECK.png'})
BATTLE = Button(area={'zh-cn': (466, 1150, 601, 1189)}, color={'zh-cn': (244, 106, 86)}, button={'zh-cn': (466, 1150, 601, 1189)}, file={'zh-cn': './assets/zh-cn/interception/BATTLE.png'})
BATTLE_QUICKLY = Button(area={'zh-cn': (505, 1077, 603, 1106)}, color={'zh-cn': (254, 154, 113)}, button={'zh-cn': (505, 1077, 603, 1106)}, file={'zh-cn': './assets/zh-cn/interception/BATTLE_QUICKLY.png'})
HARVESTER = Button(area={'zh-cn': (319, 946, 400, 983)}, color={'zh-cn': (160, 163, 162)}, button={'zh-cn': (319, 946, 400, 983)}, file={'zh-cn': './assets/zh-cn/interception/HARVESTER.png'})
INDIVILIA = Button(area={'zh-cn': (337, 941, 383, 983)}, color={'zh-cn': (166, 168, 168)}, button={'zh-cn': (337, 941, 383, 983)}, file={'zh-cn': './assets/zh-cn/interception/INDIVILIA.png'})
KRAKEN = Button(area={'zh-cn': (340, 941, 381, 982)}, color={'zh-cn': (158, 161, 160)}, button={'zh-cn': (340, 941, 381, 982)}, file={'zh-cn': './assets/zh-cn/interception/KRAKEN.png'})
MIRRORCONTAINER = Button(area={'zh-cn': (321, 945, 398, 983)}, color={'zh-cn': (176, 179, 179)}, button={'zh-cn': (321, 945, 398, 983)}, file={'zh-cn': './assets/zh-cn/interception/MIRRORCONTAINER.png'})
SWITCH = Button(area={'zh-cn': (569, 946, 596, 977)}, color={'zh-cn': (15, 75, 164)}, button={'zh-cn': (569, 946, 596, 977)}, file={'zh-cn': './assets/zh-cn/interception/SWITCH.png'})
TEAM_1 = Button(area={'zh-cn': (306, 855, 372, 877)}, color={'zh-cn': (78, 79, 81)}, button={'zh-cn': (306, 855, 372, 877)}, file={'zh-cn': './assets/zh-cn/interception/TEAM_1.png'})
TEAM_2 = Button(area={'zh-cn': (384, 855, 452, 877)}, color={'zh-cn': (81, 82, 85)}, button={'zh-cn': (384, 855, 452, 877)}, file={'zh-cn': './assets/zh-cn/interception/TEAM_2.png'})
TEAM_3 = Button(area={'zh-cn': (464, 855, 531, 878)}, color={'zh-cn': (81, 82, 85)}, button={'zh-cn': (464, 855, 531, 878)}, file={'zh-cn': './assets/zh-cn/interception/TEAM_3.png'})
TEAM_4 = Button(area={'zh-cn': (544, 855, 610, 877)}, color={'zh-cn': (83, 84, 86)}, button={'zh-cn': (544, 855, 610, 877)}, file={'zh-cn': './assets/zh-cn/interception/TEAM_4.png'})
TEAM_5 = Button(area={'zh-cn': (623, 855, 690, 877)}, color={'zh-cn': (82, 83, 85)}, button={'zh-cn': (623, 855, 690, 877)}, file={'zh-cn': './assets/zh-cn/interception/TEAM_5.png'})
TEMPLATE_RED_CIRCLE = Template(file={'zh-cn': './assets/zh-cn/interception/TEMPLATE_RED_CIRCLE.png'})
ULTRA = Button(area={'zh-cn': (340, 941, 380, 980)}, color={'zh-cn': (178, 181, 181)}, button={'zh-cn': (340, 941, 380, 980)}, file={'zh-cn': './assets/zh-cn/interception/ULTRA.png'})
