from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ARENA_SHOP_CHECK = Button(area={'zh-cn': (127, 476, 223, 504)}, color={'zh-cn': (137, 138, 139)}, button={'zh-cn': (127, 476, 223, 504)}, file={'zh-cn': './assets/zh-cn/shop/ARENA_SHOP_CHECK.png'})
BUY = Button(area={'zh-cn': (470, 1073, 505, 1095)}, color={'zh-cn': (129, 199, 232)}, button={'zh-cn': (470, 1073, 505, 1095)}, file={'zh-cn': './assets/zh-cn/shop/BUY.png'})
CANCEL = Button(area={'zh-cn': (208, 789, 255, 813)}, color={'zh-cn': (158, 157, 158)}, button={'zh-cn': (208, 789, 255, 813)}, file={'zh-cn': './assets/zh-cn/shop/CANCEL.png'})
CORE_DUST_CASE = Button(area={'zh-cn': (198, 648, 239, 671)}, color={'zh-cn': (179, 179, 180)}, button={'zh-cn': (198, 648, 239, 671)}, file={'zh-cn': './assets/zh-cn/shop/CORE_DUST_CASE.png'})
CREDIT = Button(area={'zh-cn': (561, 867, 596, 897)}, color={'zh-cn': (78, 77, 71)}, button={'zh-cn': (561, 867, 596, 897)}, file={'zh-cn': './assets/zh-cn/shop/CREDIT.png'})
ELECTRIC_CODE = Button(area={'zh-cn': (201, 706, 239, 765)}, color={'zh-cn': (168, 78, 96)}, button={'zh-cn': (201, 706, 239, 765)}, file={'zh-cn': './assets/zh-cn/shop/ELECTRIC_CODE.png'})
END_LIST_CHECK = Button(area={'zh-cn': (127, 1094, 311, 1176)}, color={'zh-cn': (238, 243, 246)}, button={'zh-cn': (127, 1094, 311, 1176)}, file={'zh-cn': './assets/zh-cn/shop/END_LIST_CHECK.png'})
FIRE_CODE = Button(area={'zh-cn': (202, 707, 240, 768)}, color={'zh-cn': (161, 78, 53)}, button={'zh-cn': (202, 707, 240, 768)}, file={'zh-cn': './assets/zh-cn/shop/FIRE_CODE.png'})
GENERAL_SHOP_CHECK = Button(area={'zh-cn': (126, 474, 190, 506)}, color={'zh-cn': (140, 140, 142)}, button={'zh-cn': (126, 474, 190, 506)}, file={'zh-cn': './assets/zh-cn/shop/GENERAL_SHOP_CHECK.png'})
GOTO_ARENA_SHOP = Button(area={'zh-cn': (31, 791, 64, 817)}, color={'zh-cn': (124, 124, 124)}, button={'zh-cn': (31, 791, 64, 817)}, file={'zh-cn': './assets/zh-cn/shop/GOTO_ARENA_SHOP.png'})
GOTO_GENERAL_SHOP = Button(area={'zh-cn': (32, 482, 69, 517)}, color={'zh-cn': (128, 126, 128)}, button={'zh-cn': (32, 482, 69, 517)}, file={'zh-cn': './assets/zh-cn/shop/GOTO_GENERAL_SHOP.png'})
GRATIS = Button(area={'zh-cn': (176, 836, 256, 848)}, color={'zh-cn': (253, 194, 126)}, button={'zh-cn': (176, 836, 256, 848)}, file={'zh-cn': './assets/zh-cn/shop/GRATIS.png'})
GRATIS_B = Button(area={'zh-cn': (194, 860, 247, 903)}, color={'zh-cn': (76, 88, 97)}, button={'zh-cn': (194, 860, 247, 903)}, file={'zh-cn': './assets/zh-cn/shop/GRATIS_B.png'})
GRATIS_REFRESH = Button(area={'zh-cn': (379, 671, 427, 697)}, color={'zh-cn': (69, 108, 139)}, button={'zh-cn': (379, 671, 427, 697)}, file={'zh-cn': './assets/zh-cn/shop/GRATIS_REFRESH.png'})
IRON_CODE = Button(area={'zh-cn': (589, 707, 621, 767)}, color={'zh-cn': (167, 123, 40)}, button={'zh-cn': (589, 707, 621, 767)}, file={'zh-cn': './assets/zh-cn/shop/IRON_CODE.png'})
MANUAL_SELECTION_BOX = Button(area={'zh-cn': (180, 1016, 258, 1064)}, color={'zh-cn': (181, 152, 117)}, button={'zh-cn': (180, 1016, 258, 1064)}, file={'zh-cn': './assets/zh-cn/shop/MANUAL_SELECTION_BOX.png'})
MAX = Button(area={'zh-cn': (590, 776, 618, 796)}, color={'zh-cn': (124, 124, 124)}, button={'zh-cn': (590, 776, 618, 796)}, file={'zh-cn': './assets/zh-cn/shop/MAX.png'})
NO_MONEY = Button(area={'zh-cn': (450, 877, 460, 911)}, color={'zh-cn': (177, 45, 41)}, button={'zh-cn': (450, 877, 460, 911)}, file={'zh-cn': './assets/zh-cn/shop/NO_MONEY.png'})
ORNAMENT = Button(area={'zh-cn': (386, 874, 442, 934)}, color={'zh-cn': (135, 130, 139)}, button={'zh-cn': (386, 874, 442, 934)}, file={'zh-cn': './assets/zh-cn/shop/ORNAMENT.png'})
PURCHASE_CHECK = Button(area={'zh-cn': (308, 211, 412, 242)}, color={'zh-cn': (115, 167, 227)}, button={'zh-cn': (308, 211, 412, 242)}, file={'zh-cn': './assets/zh-cn/shop/PURCHASE_CHECK.png'})
REFRESH = Button(area={'zh-cn': (402, 571, 425, 593)}, color={'zh-cn': (109, 111, 113)}, button={'zh-cn': (402, 571, 425, 593)}, file={'zh-cn': './assets/zh-cn/shop/REFRESH.png'})
WATER_CODE = Button(area={'zh-cn': (394, 706, 430, 768)}, color={'zh-cn': (94, 116, 133)}, button={'zh-cn': (394, 706, 430, 768)}, file={'zh-cn': './assets/zh-cn/shop/WATER_CODE.png'})
WEAPON = Button(area={'zh-cn': (578, 1007, 632, 1062)}, color={'zh-cn': (164, 95, 75)}, button={'zh-cn': (578, 1007, 632, 1062)}, file={'zh-cn': './assets/zh-cn/shop/WEAPON.png'})
WIND_CODE = Button(area={'zh-cn': (395, 708, 431, 766)}, color={'zh-cn': (94, 147, 44)}, button={'zh-cn': (395, 708, 431, 766)}, file={'zh-cn': './assets/zh-cn/shop/WIND_CODE.png'})
