from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ABNORMAL_TICKET = Button(area={'zh-cn': (168, 867, 265, 898)}, color={'zh-cn': (198, 199, 200)}, button={'zh-cn': (168, 867, 265, 898)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/ABNORMAL_TICKET.png'})
BATTLE_DATA_SET_CASE = Button(area={'zh-cn': (541, 816, 605, 837)}, color={'zh-cn': (165, 165, 166)}, button={'zh-cn': (541, 816, 605, 837)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/BATTLE_DATA_SET_CASE.png'})
BROKEN_CORE_NUM = Button(area={'zh-cn': (359, 694, 460, 715)}, color={'zh-cn': (226, 226, 226)}, button={'zh-cn': (359, 694, 460, 715)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/BROKEN_CORE_NUM.png'})
BUY = Button(area={'zh-cn': (469, 1044, 516, 1059)}, color={'zh-cn': (133, 202, 235)}, button={'zh-cn': (469, 1044, 516, 1059)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/BUY.png'})
CANCEL = Button(area={'zh-cn': (246, 1044, 290, 1067)}, color={'zh-cn': (156, 156, 158)}, button={'zh-cn': (246, 1044, 290, 1067)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/CANCEL.png'})
CORE_DUST_CASE = Button(area={'zh-cn': (183, 886, 225, 907)}, color={'zh-cn': (173, 173, 175)}, button={'zh-cn': (183, 886, 225, 907)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/CORE_DUST_CASE.png'})
CREDIT_CASE = Button(area={'zh-cn': (377, 885, 443, 908)}, color={'zh-cn': (171, 171, 172)}, button={'zh-cn': (377, 885, 443, 908)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/CREDIT_CASE.png'})
CURATED_MANUFACTURER_ARMS = Button(area={'zh-cn': (580, 715, 607, 729)}, color={'zh-cn': (110, 79, 68)}, button={'zh-cn': (580, 715, 607, 729)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/CURATED_MANUFACTURER_ARMS.png'})
ELYSION_TICKET = Button(area={'zh-cn': (588, 713, 622, 754)}, color={'zh-cn': (215, 166, 160)}, button={'zh-cn': (588, 713, 622, 754)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/ELYSION_TICKET.png'})
GEM = Button(area={'zh-cn': (192, 646, 239, 671)}, color={'zh-cn': (179, 180, 181)}, button={'zh-cn': (192, 646, 239, 671)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/GEM.png'})
GENERAL_TICKET = Button(area={'zh-cn': (398, 723, 433, 755)}, color={'zh-cn': (229, 219, 212)}, button={'zh-cn': (398, 723, 433, 755)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/GENERAL_TICKET.png'})
GOOD_TEAMWORK_BOX = Button(area={'zh-cn': (192, 737, 211, 757)}, color={'zh-cn': (143, 144, 164)}, button={'zh-cn': (192, 737, 211, 757)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/GOOD_TEAMWORK_BOX.png'})
GOTO_RUBBISH_SHOP = Button(area={'zh-cn': (31, 990, 71, 1025)}, color={'zh-cn': (141, 141, 143)}, button={'zh-cn': (31, 990, 71, 1025)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/GOTO_RUBBISH_SHOP.png'})
MAINTENANCE_KIT_BOX_2 = Button(area={'zh-cn': (393, 727, 430, 742)}, color={'zh-cn': (226, 177, 130)}, button={'zh-cn': (393, 727, 430, 742)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/MAINTENANCE_KIT_BOX_2.png'})
MISSILIS_TICKET = Button(area={'zh-cn': (209, 1015, 248, 1069)}, color={'zh-cn': (137, 127, 107)}, button={'zh-cn': (209, 1015, 248, 1069)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/MISSILIS_TICKET.png'})
PILGRIM_TICKET = Button(area={'zh-cn': (584, 1022, 623, 1068)}, color={'zh-cn': (169, 157, 195)}, button={'zh-cn': (584, 1022, 623, 1068)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/PILGRIM_TICKET.png'})
RUBBISH_SHOP_CHECK = Button(area={'zh-cn': (127, 474, 190, 506)}, color={'zh-cn': (137, 137, 139)}, button={'zh-cn': (127, 474, 190, 506)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/RUBBISH_SHOP_CHECK.png'})
TETRA_TICKET = Button(area={'zh-cn': (399, 1017, 432, 1066)}, color={'zh-cn': (158, 132, 115)}, button={'zh-cn': (399, 1017, 432, 1066)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/TETRA_TICKET.png'})
