from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ABNORMAL_TICKET = Button(area={'zh-cn': (196, 1047, 233, 1058)}, color={'zh-cn': (141, 156, 179)}, button={'zh-cn': (196, 1047, 233, 1058)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/ABNORMAL_TICKET.png'})
BATTLE_DATA_SET_CASE = Button(area={'zh-cn': (588, 1034, 624, 1058)}, color={'zh-cn': (121, 127, 131)}, button={'zh-cn': (588, 1034, 624, 1058)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/BATTLE_DATA_SET_CASE.png'})
BROKEN_CORE_NUM = Button(area={'zh-cn': (359, 694, 460, 715)}, color={'zh-cn': (226, 226, 226)}, button={'zh-cn': (359, 694, 460, 715)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/BROKEN_CORE_NUM.png'})
BUY = Button(area={'zh-cn': (469, 1044, 516, 1059)}, color={'zh-cn': (133, 202, 235)}, button={'zh-cn': (469, 1044, 516, 1059)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/BUY.png'})
CANCEL = Button(area={'zh-cn': (246, 1044, 290, 1067)}, color={'zh-cn': (156, 156, 158)}, button={'zh-cn': (246, 1044, 290, 1067)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/CANCEL.png'})
CORE_DUST_CASE = Button(area={'zh-cn': (203, 1039, 239, 1064)}, color={'zh-cn': (124, 124, 128)}, button={'zh-cn': (203, 1039, 239, 1064)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/CORE_DUST_CASE.png'})
CREDIT = Button(area={'zh-cn': (384, 1051, 405, 1068)}, color={'zh-cn': (168, 153, 130)}, button={'zh-cn': (384, 1051, 405, 1068)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/CREDIT.png'})
CREDIT_CASE = Button(area={'zh-cn': (395, 1030, 434, 1058)}, color={'zh-cn': (118, 121, 123)}, button={'zh-cn': (395, 1030, 434, 1058)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/CREDIT_CASE.png'})
CURATED_MANUFACTURER_ARMS = Button(area={'zh-cn': (582, 760, 614, 771)}, color={'zh-cn': (86, 80, 72)}, button={'zh-cn': (582, 760, 614, 771)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/CURATED_MANUFACTURER_ARMS.png'})
ELYSION_TICKET = Button(area={'zh-cn': (571, 767, 624, 785)}, color={'zh-cn': (202, 195, 191)}, button={'zh-cn': (571, 767, 624, 785)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/ELYSION_TICKET.png'})
GEM = Button(area={'zh-cn': (200, 765, 231, 786)}, color={'zh-cn': (103, 149, 209)}, button={'zh-cn': (200, 765, 231, 786)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/GEM.png'})
GENERAL_TICKET = Button(area={'zh-cn': (378, 771, 432, 787)}, color={'zh-cn': (207, 207, 203)}, button={'zh-cn': (378, 771, 432, 787)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/GENERAL_TICKET.png'})
GOOD_TEAMWORK_BOX = Button(area={'zh-cn': (191, 754, 229, 769)}, color={'zh-cn': (154, 154, 157)}, button={'zh-cn': (191, 754, 229, 769)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/GOOD_TEAMWORK_BOX.png'})
GOTO_RUBBISH_SHOP = Button(area={'zh-cn': (31, 990, 71, 1025)}, color={'zh-cn': (141, 141, 143)}, button={'zh-cn': (31, 990, 71, 1025)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/GOTO_RUBBISH_SHOP.png'})
GROWTH_SET = Button(area={'zh-cn': (201, 1055, 238, 1069)}, color={'zh-cn': (169, 158, 159)}, button={'zh-cn': (201, 1055, 238, 1069)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/GROWTH_SET.png'})
MAINTENANCE_KIT_BOX_2 = Button(area={'zh-cn': (385, 756, 422, 770)}, color={'zh-cn': (149, 141, 137)}, button={'zh-cn': (385, 756, 422, 770)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/MAINTENANCE_KIT_BOX_2.png'})
MISSILIS_TICKET = Button(area={'zh-cn': (188, 1079, 238, 1093)}, color={'zh-cn': (183, 174, 145)}, button={'zh-cn': (188, 1079, 238, 1093)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/MISSILIS_TICKET.png'})
ORNAMENT = Button(area={'zh-cn': (386, 874, 442, 934)}, color={'zh-cn': (135, 130, 139)}, button={'zh-cn': (386, 874, 442, 934)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/ORNAMENT.png'})
PILGRIM_TICKET = Button(area={'zh-cn': (578, 1081, 619, 1093)}, color={'zh-cn': (196, 163, 181)}, button={'zh-cn': (578, 1081, 619, 1093)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/PILGRIM_TICKET.png'})
RUBBISH_SHOP_CHECK = Button(area={'zh-cn': (127, 474, 190, 506)}, color={'zh-cn': (137, 137, 139)}, button={'zh-cn': (127, 474, 190, 506)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/RUBBISH_SHOP_CHECK.png'})
TETRA_TICKET = Button(area={'zh-cn': (383, 1079, 431, 1093)}, color={'zh-cn': (158, 143, 134)}, button={'zh-cn': (383, 1079, 431, 1093)}, file={'zh-cn': './assets/zh-cn/rubbish_shop/TETRA_TICKET.png'})
