from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COOP_ACCEPT = Button(area={'zh-cn': (503, 863, 549, 887)}, color={'zh-cn': (124, 200, 236)}, button={'zh-cn': (503, 863, 549, 887)}, file={'zh-cn': './assets/zh-cn/coop/COOP_ACCEPT.png'})
COOP_BANNER_CHECK = Button(area={'zh-cn': (224, 153, 264, 175)}, color={'zh-cn': (138, 138, 135)}, button={'zh-cn': (224, 153, 264, 175)}, file={'zh-cn': './assets/zh-cn/coop/COOP_BANNER_CHECK.png'})
COOP_CANCEL = Button(area={'zh-cn': (625, 138, 661, 156)}, color={'zh-cn': (131, 131, 131)}, button={'zh-cn': (625, 138, 661, 156)}, file={'zh-cn': './assets/zh-cn/coop/COOP_CANCEL.png'})
COOP_CHECK = Button(area={'zh-cn': (458, 182, 608, 205)}, color={'zh-cn': (75, 75, 73)}, button={'zh-cn': (458, 182, 608, 205)}, file={'zh-cn': './assets/zh-cn/coop/COOP_CHECK.png'})
COOP_PREPARE = Button(area={'zh-cn': (334, 1195, 386, 1220)}, color={'zh-cn': (148, 199, 249)}, button={'zh-cn': (334, 1195, 386, 1220)}, file={'zh-cn': './assets/zh-cn/coop/COOP_PREPARE.png'})
COOP_ROLE_CHECK = Button(area={'zh-cn': (476, 640, 588, 662)}, color={'zh-cn': (105, 105, 104)}, button={'zh-cn': (476, 640, 588, 662)}, file={'zh-cn': './assets/zh-cn/coop/COOP_ROLE_CHECK.png'})
COOP_START = Button(area={'zh-cn': (477, 979, 587, 1005)}, color={'zh-cn': (250, 149, 136)}, button={'zh-cn': (477, 979, 587, 1005)}, file={'zh-cn': './assets/zh-cn/coop/COOP_START.png'})
DATELINE_CHECK = Button(area={'zh-cn': (501, 278, 669, 311)}, color={'zh-cn': (72, 57, 30)}, button={'zh-cn': (501, 278, 669, 311)}, file={'zh-cn': './assets/zh-cn/coop/DATELINE_CHECK.png'})
DIFFICULTY_CONFIRM = Button(area={'zh-cn': (334, 854, 385, 877)}, color={'zh-cn': (120, 207, 247)}, button={'zh-cn': (334, 854, 385, 877)}, file={'zh-cn': './assets/zh-cn/coop/DIFFICULTY_CONFIRM.png'})
DIFFICULTY_NORMAL = Button(area={'zh-cn': (180, 611, 248, 643)}, color={'zh-cn': (155, 223, 255)}, button={'zh-cn': (180, 611, 248, 643)}, file={'zh-cn': './assets/zh-cn/coop/DIFFICULTY_NORMAL.png'})
DIFFICULTY_NORMAL_NOT_CHECKED = Button(area={'zh-cn': (181, 611, 247, 643)}, color={'zh-cn': (192, 193, 192)}, button={'zh-cn': (181, 611, 247, 643)}, file={'zh-cn': './assets/zh-cn/coop/DIFFICULTY_NORMAL_NOT_CHECKED.png'})
EVENT_BANNER = Button(area={'zh-cn': (29, 121, 267, 187)}, color={'zh-cn': (116, 74, 67)}, button={'zh-cn': (29, 121, 267, 187)}, file={'zh-cn': './assets/zh-cn/coop/EVENT_BANNER.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'zh-cn': (442, 1006, 625, 1036)}, color={'zh-cn': (255, 150, 44)}, button={'zh-cn': (442, 1006, 625, 1036)}, file={'zh-cn': './assets/zh-cn/coop/FREE_OPPORTUNITY_CHECK.png'})
SECECT_DIFFICULTY = Button(area={'zh-cn': (282, 513, 408, 533)}, color={'zh-cn': (170, 170, 170)}, button={'zh-cn': (282, 513, 408, 533)}, file={'zh-cn': './assets/zh-cn/coop/SECECT_DIFFICULTY.png'})
