from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ANSWER_CHECK = Button(area={'cn': (68, 852, 90, 902)}, color={'cn': (9, 28, 40)}, button={'cn': (68, 852, 90, 902)}, file={'cn': './assets/cn/conversation/ANSWER_CHECK.png'})
CASE_CLOSED = Button(area={'cn': (583, 637, 686, 647)}, color={'cn': (103, 205, 250)}, button={'cn': (583, 637, 686, 647)}, file={'cn': './assets/cn/conversation/CASE_CLOSED.png'})
COMMUNICATE = Button(area={'cn': (460, 1017, 559, 1064)}, color={'cn': (87, 149, 207)}, button={'cn': (460, 1017, 559, 1064)}, file={'cn': './assets/cn/conversation/COMMUNICATE.png'})
COMMUNICATE_DONE = Button(area={'cn': (462, 1023, 560, 1058)}, color={'cn': (87, 88, 89)}, button={'cn': (462, 1023, 560, 1058)}, file={'cn': './assets/cn/conversation/COMMUNICATE_DONE.png'})
COMMUNICATE_NIKKE_AVATAR = Button(area={'cn': (554, 648, 679, 773)}, color={'cn': (131, 113, 117)}, button={'cn': (554, 648, 679, 773)}, file={'cn': './assets/cn/conversation/COMMUNICATE_NIKKE_AVATAR.png'})
COMMUNICATE_NIKKE_NAME = Button(area={'cn': (47, 771, 520, 825)}, color={'cn': (196, 198, 199)}, button={'cn': (47, 771, 520, 825)}, file={'cn': './assets/cn/conversation/COMMUNICATE_NIKKE_NAME.png'})
COMMUNICATE_QUICKLY = Button(area={'cn': (472, 952, 580, 988)}, color={'cn': (254, 143, 101)}, button={'cn': (472, 952, 580, 988)}, file={'cn': './assets/cn/conversation/COMMUNICATE_QUICKLY.png'})
DETAIL_CHECK = Button(area={'cn': (514, 1173, 621, 1197)}, color={'cn': (254, 141, 129)}, button={'cn': (514, 1173, 621, 1197)}, file={'cn': './assets/cn/conversation/DETAIL_CHECK.png'})
FAVOURITE_CHECK = Button(area={'cn': (134, 371, 159, 400)}, color={'cn': (254, 83, 69)}, button={'cn': (134, 371, 159, 400)}, file={'cn': './assets/cn/conversation/FAVOURITE_CHECK.png'})
GIFT = Button(area={'cn': (160, 1018, 225, 1059)}, color={'cn': (254, 177, 79)}, button={'cn': (160, 1018, 225, 1059)}, file={'cn': './assets/cn/conversation/GIFT.png'})
OPPORTUNITY = Button(area={'cn': (83, 295, 183, 325)}, color={'cn': (70, 192, 249)}, button={'cn': (83, 295, 183, 325)}, file={'cn': './assets/cn/conversation/OPPORTUNITY.png'})
OPPORTUNITY_B = Button(area={'cn': (506, 1068, 541, 1087)}, color={'cn': (192, 191, 194)}, button={'cn': (506, 1068, 541, 1087)}, file={'cn': './assets/cn/conversation/OPPORTUNITY_B.png'})
RANK_INCREASE_CHECK = Button(area={'cn': (233, 660, 389, 704)}, color={'cn': (90, 50, 78)}, button={'cn': (233, 660, 389, 704)}, file={'cn': './assets/cn/conversation/RANK_INCREASE_CHECK.png'})
RANK_INCREASE_COMFIRM = Button(area={'cn': (295, 1079, 387, 1096)}, color={'cn': (145, 150, 152)}, button={'cn': (295, 1079, 387, 1096)}, file={'cn': './assets/cn/conversation/RANK_INCREASE_COMFIRM.png'})
RANK_MAX_CHECK = Button(area={'cn': (465, 828, 510, 843)}, color={'cn': (241, 168, 163)}, button={'cn': (465, 828, 510, 843)}, file={'cn': './assets/cn/conversation/RANK_MAX_CHECK.png'})
TEMPLATE_ANSWER_CHECK = Template(file={'cn': './assets/cn/conversation/TEMPLATE_ANSWER_CHECK.png'})
TEMPLATE_ANSWER_TRUE = Template(file={'cn': './assets/cn/conversation/TEMPLATE_ANSWER_TRUE.png'})
