from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ANSWER_CHECK = Button(area={'zh-CN': (631, 832, 652, 882)}, color={'zh-CN': (15, 31, 45)}, button={'zh-CN': (631, 832, 652, 882)}, file={'zh-CN': './assets/zh-CN/conversation/ANSWER_CHECK.png'})
CASE_CLOSED = Button(area={'zh-CN': (583, 637, 686, 647)}, color={'zh-CN': (103, 205, 250)}, button={'zh-CN': (583, 637, 686, 647)}, file={'zh-CN': './assets/zh-CN/conversation/CASE_CLOSED.png'})
COMMUNICATE = Button(area={'zh-CN': (460, 1017, 559, 1064)}, color={'zh-CN': (87, 149, 207)}, button={'zh-CN': (460, 1017, 559, 1064)}, file={'zh-CN': './assets/zh-CN/conversation/COMMUNICATE.png'})
COMMUNICATE_DONE = Button(area={'zh-CN': (462, 1023, 560, 1058)}, color={'zh-CN': (87, 88, 89)}, button={'zh-CN': (462, 1023, 560, 1058)}, file={'zh-CN': './assets/zh-CN/conversation/COMMUNICATE_DONE.png'})
COMMUNICATE_LOGS_QUANTITY = Button(area={'zh-CN': (573, 794, 682, 864)}, color={'zh-CN': (228, 222, 223)}, button={'zh-CN': (573, 794, 682, 864)}, file={'zh-CN': './assets/zh-CN/conversation/COMMUNICATE_LOGS_QUANTITY.png'})
COMMUNICATE_NIKKE_AVATAR = Button(area={'zh-CN': (554, 648, 679, 773)}, color={'zh-CN': (131, 113, 117)}, button={'zh-CN': (554, 648, 679, 773)}, file={'zh-CN': './assets/zh-CN/conversation/COMMUNICATE_NIKKE_AVATAR.png'})
COMMUNICATE_NIKKE_NAME = Button(area={'zh-CN': (47, 771, 520, 825)}, color={'zh-CN': (196, 198, 199)}, button={'zh-CN': (47, 771, 520, 825)}, file={'zh-CN': './assets/zh-CN/conversation/COMMUNICATE_NIKKE_NAME.png'})
COMMUNICATE_QUICKLY = Button(area={'zh-CN': (472, 952, 580, 988)}, color={'zh-CN': (254, 143, 101)}, button={'zh-CN': (472, 952, 580, 988)}, file={'zh-CN': './assets/zh-CN/conversation/COMMUNICATE_QUICKLY.png'})
DETAIL_CHECK = Button(area={'zh-CN': (514, 1173, 621, 1197)}, color={'zh-CN': (254, 141, 129)}, button={'zh-CN': (514, 1173, 621, 1197)}, file={'zh-CN': './assets/zh-CN/conversation/DETAIL_CHECK.png'})
FAVOURITE = Button(area={'zh-CN': (52, 663, 95, 705)}, color={'zh-CN': (252, 91, 76)}, button={'zh-CN': (52, 663, 95, 705)}, file={'zh-CN': './assets/zh-CN/conversation/FAVOURITE.png'})
FAVOURITE_CHECK = Button(area={'zh-CN': (134, 371, 159, 400)}, color={'zh-CN': (254, 83, 69)}, button={'zh-CN': (134, 371, 159, 400)}, file={'zh-CN': './assets/zh-CN/conversation/FAVOURITE_CHECK.png'})
GIFT = Button(area={'zh-CN': (160, 1018, 225, 1059)}, color={'zh-CN': (254, 177, 79)}, button={'zh-CN': (160, 1018, 225, 1059)}, file={'zh-CN': './assets/zh-CN/conversation/GIFT.png'})
OPPORTUNITY = Button(area={'zh-CN': (86, 291, 292, 324)}, color={'zh-CN': (56, 185, 246)}, button={'zh-CN': (86, 291, 292, 324)}, file={'zh-CN': './assets/zh-CN/conversation/OPPORTUNITY.png'})
OPPORTUNITY_B = Button(area={'zh-CN': (506, 1068, 541, 1087)}, color={'zh-CN': (192, 191, 194)}, button={'zh-CN': (506, 1068, 541, 1087)}, file={'zh-CN': './assets/zh-CN/conversation/OPPORTUNITY_B.png'})
RANK_INCREASE_CHECK = Button(area={'zh-CN': (233, 660, 389, 704)}, color={'zh-CN': (90, 50, 78)}, button={'zh-CN': (233, 660, 389, 704)}, file={'zh-CN': './assets/zh-CN/conversation/RANK_INCREASE_CHECK.png'})
RANK_INCREASE_COMFIRM = Button(area={'zh-CN': (295, 1079, 387, 1096)}, color={'zh-CN': (145, 150, 152)}, button={'zh-CN': (295, 1079, 387, 1096)}, file={'zh-CN': './assets/zh-CN/conversation/RANK_INCREASE_COMFIRM.png'})
RANK_MAX_CHECK = Button(area={'zh-CN': (465, 828, 510, 843)}, color={'zh-CN': (241, 168, 163)}, button={'zh-CN': (465, 828, 510, 843)}, file={'zh-CN': './assets/zh-CN/conversation/RANK_MAX_CHECK.png'})
TEMPLATE_ANSWER_CHECK = Template(file={'zh-CN': './assets/zh-CN/conversation/TEMPLATE_ANSWER_CHECK.png'})
TEMPLATE_ANSWER_TRUE = Template(file={'zh-CN': './assets/zh-CN/conversation/TEMPLATE_ANSWER_TRUE.png'})
