from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CONNECT_TO_SYSTEM = Button(area={'zh-cn': (351, 652, 382, 667)}, color={'zh-cn': (168, 169, 170)}, button={'zh-cn': (351, 652, 382, 667)}, file={'zh-cn': './assets/zh-cn/rookie_arena/CONNECT_TO_SYSTEM.png'})
END_COMPETITION = Button(area={'zh-cn': (45, 1194, 86, 1236)}, color={'zh-cn': (117, 116, 117)}, button={'zh-cn': (45, 1194, 86, 1236)}, file={'zh-cn': './assets/zh-cn/rookie_arena/END_COMPETITION.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'zh-cn': (580, 677, 619, 698)}, color={'zh-cn': (120, 195, 237)}, button={'zh-cn': (580, 677, 619, 698)}, file={'zh-cn': './assets/zh-cn/rookie_arena/FREE_OPPORTUNITY_CHECK.png'})
INTO_COMPETITION = Button(area={'zh-cn': (294, 1035, 421, 1064)}, color={'zh-cn': (130, 178, 219)}, button={'zh-cn': (294, 1035, 421, 1064)}, file={'zh-cn': './assets/zh-cn/rookie_arena/INTO_COMPETITION.png'})
NEXT_SEASON = Button(area={'zh-cn': (146, 588, 212, 603)}, color={'zh-cn': (48, 55, 58)}, button={'zh-cn': (146, 588, 212, 603)}, file={'zh-cn': './assets/zh-cn/rookie_arena/NEXT_SEASON.png'})
OWN_POWER_CHECK = Button(area={'zh-cn': (530, 369, 550, 388)}, color={'zh-cn': (117, 120, 122)}, button={'zh-cn': (530, 369, 550, 388)}, file={'zh-cn': './assets/zh-cn/rookie_arena/OWN_POWER_CHECK.png'})
POWER_CHECK = Button(area={'zh-cn': (428, 668, 446, 686)}, color={'zh-cn': (195, 196, 197)}, button={'zh-cn': (428, 668, 446, 686)}, file={'zh-cn': './assets/zh-cn/rookie_arena/POWER_CHECK.png'})
SKIP = Button(area={'zh-cn': (226, 1060, 276, 1077)}, color={'zh-cn': (148, 148, 148)}, button={'zh-cn': (226, 1060, 276, 1077)}, file={'zh-cn': './assets/zh-cn/rookie_arena/SKIP.png'})
