from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DESTROY = Button(area={'zh-CN': (305, 931, 629, 996), 'en-US': (285, 951, 645, 1010)}, color={'zh-CN': (28, 179, 247), 'en-US': (23, 178, 244)}, button={'zh-CN': (305, 931, 629, 996), 'en-US': (285, 951, 645, 1010)}, file={'zh-CN': './assets/zh-CN/destruction/DESTROY.png', 'en-US': './assets/en-US/destruction/DESTROY.png'})
DESTROY_CHECK = Button(area={'zh-CN': (310, 1015, 368, 1071), 'en-US': (310, 1015, 368, 1071)}, color={'zh-CN': (240, 237, 239), 'en-US': (240, 237, 239)}, button={'zh-CN': (310, 1015, 368, 1071), 'en-US': (310, 1015, 368, 1071)}, file={'zh-CN': './assets/zh-CN/destruction/DESTROY_CHECK.png', 'en-US': './assets/en-US/destruction/DESTROY_CHECK.png'})
