from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/event_button_extract.py.
# Don't modify it manually.

CHALLENGE = Button(area={'cn': (195, 905, 238, 924)}, color={'cn': (94, 94, 96)}, button={'cn': (195, 905, 238, 924)}, file={'cn': './assets/event/event_20250807/CHALLENGE.png'})
EVENT_CHECK = Button(area={'cn': (556, 1079, 626, 1115)}, color={'cn': (127, 129, 135)}, button={'cn': (556, 1079, 626, 1115)}, file={'cn': './assets/event/event_20250807/EVENT_CHECK.png'})
MAIN_GOTO_EVENT = Button(area={'cn': (602, 1068, 642, 1083)}, color={'cn': (151, 132, 146)}, button={'cn': (602, 1068, 642, 1083)}, file={'cn': './assets/event/event_20250807/MAIN_GOTO_EVENT.png'})
RECEIVE = Button(area={'cn': (297, 811, 423, 832)}, color={'cn': (58, 59, 61)}, button={'cn': (297, 811, 423, 832)}, file={'cn': './assets/event/event_20250807/RECEIVE.png'})
REWARD = Button(area={'cn': (219, 972, 259, 990)}, color={'cn': (95, 94, 96)}, button={'cn': (219, 972, 259, 990)}, file={'cn': './assets/event/event_20250807/REWARD.png'})
REWARD_CHECK = Button(area={'cn': (196, 99, 273, 142)}, color={'cn': (118, 113, 109)}, button={'cn': (196, 99, 273, 142)}, file={'cn': './assets/event/event_20250807/REWARD_CHECK.png'})
REWARD_CLOSED = Button(area={'cn': (643, 66, 676, 96)}, color={'cn': (109, 98, 92)}, button={'cn': (643, 66, 676, 96)}, file={'cn': './assets/event/event_20250807/REWARD_CLOSED.png'})
REWARD_RECEIVE = Button(area={'cn': (498, 1132, 607, 1153)}, color={'cn': (198, 173, 115)}, button={'cn': (498, 1132, 607, 1153)}, file={'cn': './assets/event/event_20250807/REWARD_RECEIVE.png'})
REWARD_RECEIVE_DONE = Button(area={'cn': (496, 1131, 607, 1151)}, color={'cn': (142, 140, 141)}, button={'cn': (496, 1131, 607, 1151)}, file={'cn': './assets/event/event_20250807/REWARD_RECEIVE_DONE.png'})
SHOP = Button(area={'cn': (192, 1036, 232, 1055)}, color={'cn': (97, 97, 99)}, button={'cn': (192, 1036, 232, 1055)}, file={'cn': './assets/event/event_20250807/SHOP.png'})
SHOP_ITEM_LOAD_CHECK = Button(area={'cn': (576, 1031, 607, 1056)}, color={'cn': (116, 78, 75)}, button={'cn': (576, 1031, 607, 1056)}, file={'cn': './assets/event/event_20250807/SHOP_ITEM_LOAD_CHECK.png'})
SKIP = Button(area={'cn': (616, 22, 671, 41)}, color={'cn': (133, 134, 133)}, button={'cn': (616, 22, 671, 41)}, file={'cn': './assets/event/event_20250807/SKIP.png'})
STORY_1_CHECK = Button(area={'cn': (417, 1080, 589, 1135)}, color={'cn': (197, 209, 227)}, button={'cn': (417, 1080, 589, 1135)}, file={'cn': './assets/event/event_20250807/STORY_1_CHECK.png'})
STORY_1_HARD = Button(area={'cn': (615, 1160, 665, 1233)}, color={'cn': (158, 81, 127)}, button={'cn': (615, 1160, 665, 1233)}, file={'cn': './assets/event/event_20250807/STORY_1_HARD.png'})
STORY_1_HARD_HIDDEN = Button(area={'cn': (612, 1157, 666, 1238)}, color={'cn': (50, 52, 52)}, button={'cn': (612, 1157, 666, 1238)}, file={'cn': './assets/event/event_20250807/STORY_1_HARD_HIDDEN.png'})
STORY_1_HARD_LOCKED = Button(area={'cn': (548, 1151, 683, 1169)}, color={'cn': (119, 122, 126)}, button={'cn': (548, 1151, 683, 1169)}, file={'cn': './assets/event/event_20250807/STORY_1_HARD_LOCKED.png'})
STORY_1_HARD_STAGE_11 = Button(area={'cn': (146, 785, 375, 819)}, color={'cn': (90, 93, 102)}, button={'cn': (146, 785, 375, 819)}, file={'cn': './assets/event/event_20250807/STORY_1_HARD_STAGE_11.png'})
STORY_1_HARD_UNLOCK = Button(area={'cn': (343, 733, 438, 753)}, color={'cn': (157, 161, 163)}, button={'cn': (343, 733, 438, 753)}, file={'cn': './assets/event/event_20250807/STORY_1_HARD_UNLOCK.png'})
STORY_1_NORMAL = Button(area={'cn': (445, 1162, 517, 1231)}, color={'cn': (148, 141, 130)}, button={'cn': (445, 1162, 517, 1231)}, file={'cn': './assets/event/event_20250807/STORY_1_NORMAL.png'})
STORY_1_NORMAL_STAGE_11 = Button(area={'cn': (115, 858, 373, 884)}, color={'cn': (193, 189, 210)}, button={'cn': (115, 858, 373, 884)}, file={'cn': './assets/event/event_20250807/STORY_1_NORMAL_STAGE_11.png'})
STORY_2_HARD_STAGE_11 = Button(area={'cn': (404, 588, 439, 664)}, color={'cn': (150, 150, 149)}, button={'cn': (404, 588, 439, 664)}, file={'cn': './assets/event/event_20250807/STORY_2_HARD_STAGE_11.png'})
STORY_2_NORMAL_STAGE_11 = Button(area={'cn': (317, 746, 404, 788)}, color={'cn': (85, 117, 141)}, button={'cn': (317, 746, 404, 788)}, file={'cn': './assets/event/event_20250807/STORY_2_NORMAL_STAGE_11.png'})
STORY_STAGE_CHECK = Button(area={'cn': (138, 860, 234, 882)}, color={'cn': (177, 177, 177)}, button={'cn': (138, 860, 234, 882)}, file={'cn': './assets/event/event_20250807/STORY_STAGE_CHECK.png'})
TEMPLATE_SHOP_MONEY = Template(file={'cn': './assets/event/event_20250807/TEMPLATE_SHOP_MONEY.png'})
