from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

NO_REWARDS = Button(area={'cn': (386, 531, 632, 568)}, color={'cn': (191, 179, 178)}, button={'cn': (386, 531, 632, 568)}, file={'cn': './assets/cn/reward/NO_REWARDS.png'})
NO_REWARDS_1 = Button(area={'cn': (263, 870, 439, 887)}, color={'cn': (224, 224, 224)}, button={'cn': (263, 870, 439, 887)}, file={'cn': './assets/cn/reward/NO_REWARDS_1.png'})
NO_REWARDS_2 = Button(area={'cn': (620, 750, 663, 786)}, color={'cn': (81, 84, 93)}, button={'cn': (620, 750, 663, 786)}, file={'cn': './assets/cn/reward/NO_REWARDS_2.png'})
NO_REWARDS_3 = Button(area={'cn': (438, 754, 603, 778)}, color={'cn': (69, 81, 99)}, button={'cn': (438, 754, 603, 778)}, file={'cn': './assets/cn/reward/NO_REWARDS_3.png'})
RANKING_ARENA = Button(area={'cn': (0, 185, 720, 1152)}, color={'cn': (177, 171, 169)}, button={'cn': (0, 185, 720, 1152)}, file={'cn': './assets/cn/reward/RANKING_ARENA.png'})
RANKING_FRONT_CHECK = Button(area={'cn': (551, 1198, 676, 1220)}, color={'cn': (126, 198, 232)}, button={'cn': (551, 1198, 676, 1220)}, file={'cn': './assets/cn/reward/RANKING_FRONT_CHECK.png'})
RANKING_LOAD_CHECK = Button(area={'cn': (557, 842, 569, 883)}, color={'cn': (88, 164, 224)}, button={'cn': (557, 842, 569, 883)}, file={'cn': './assets/cn/reward/RANKING_LOAD_CHECK.png'})
RANKING_NO_REWARD = Button(area={'cn': (529, 1063, 642, 1088)}, color={'cn': (175, 172, 172)}, button={'cn': (529, 1063, 642, 1088)}, file={'cn': './assets/cn/reward/RANKING_NO_REWARD.png'})
RANKING_RECEIVE = Button(area={'cn': (298, 813, 424, 831)}, color={'cn': (80, 79, 79)}, button={'cn': (298, 813, 424, 831)}, file={'cn': './assets/cn/reward/RANKING_RECEIVE.png'})
RANKING_RED_POINT_CHECK = Button(area={'cn': (675, 179, 694, 198)}, color={'cn': (152, 98, 80)}, button={'cn': (675, 179, 694, 198)}, file={'cn': './assets/cn/reward/RANKING_RED_POINT_CHECK.png'})
RANKING_REWARD = Button(area={'cn': (531, 1062, 644, 1088)}, color={'cn': (142, 160, 178)}, button={'cn': (531, 1062, 644, 1088)}, file={'cn': './assets/cn/reward/RANKING_REWARD.png'})
RECEIVE = Button(area={'cn': (426, 1047, 471, 1090)}, color={'cn': (67, 191, 249)}, button={'cn': (426, 1047, 471, 1090)}, file={'cn': './assets/cn/reward/RECEIVE.png'})
RECEIVE_SPECIAL_ARENA_POINT = Button(area={'cn': (296, 299, 310, 332)}, color={'cn': (174, 206, 151)}, button={'cn': (296, 299, 310, 332)}, file={'cn': './assets/cn/reward/RECEIVE_SPECIAL_ARENA_POINT.png'})
REWARD = Button(area={'cn': (445, 1125, 541, 1150)}, color={'cn': (128, 198, 233)}, button={'cn': (445, 1125, 541, 1150)}, file={'cn': './assets/cn/reward/REWARD.png'})
REWARD_B = Button(area={'cn': (477, 1122, 532, 1152)}, color={'cn': (91, 185, 232)}, button={'cn': (477, 1122, 532, 1152)}, file={'cn': './assets/cn/reward/REWARD_B.png'})
SEND_AND_RECEIVE = Button(area={'cn': (508, 1075, 589, 1101)}, color={'cn': (129, 213, 251)}, button={'cn': (508, 1075, 589, 1101)}, file={'cn': './assets/cn/reward/SEND_AND_RECEIVE.png'})
TEMPLATE_RANKING_RED_POINT = Template(file={'cn': './assets/cn/reward/TEMPLATE_RANKING_RED_POINT.png'})
