from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

NO_REWARDS = Button(area={'zh-cn': (386, 531, 632, 568)}, color={'zh-cn': (191, 179, 178)}, button={'zh-cn': (386, 531, 632, 568)}, file={'zh-cn': './assets/zh-cn/reward/NO_REWARDS.png'})
NO_REWARDS_1 = Button(area={'zh-cn': (263, 870, 439, 887)}, color={'zh-cn': (224, 224, 224)}, button={'zh-cn': (263, 870, 439, 887)}, file={'zh-cn': './assets/zh-cn/reward/NO_REWARDS_1.png'})
NO_REWARDS_2 = Button(area={'zh-cn': (620, 750, 663, 786)}, color={'zh-cn': (81, 84, 93)}, button={'zh-cn': (620, 750, 663, 786)}, file={'zh-cn': './assets/zh-cn/reward/NO_REWARDS_2.png'})
NO_REWARDS_3 = Button(area={'zh-cn': (438, 754, 603, 778)}, color={'zh-cn': (69, 81, 99)}, button={'zh-cn': (438, 754, 603, 778)}, file={'zh-cn': './assets/zh-cn/reward/NO_REWARDS_3.png'})
RANKING_NO_REWARD = Button(area={'zh-cn': (550, 1195, 579, 1221)}, color={'zh-cn': (143, 140, 141)}, button={'zh-cn': (550, 1195, 579, 1221)}, file={'zh-cn': './assets/zh-cn/reward/RANKING_NO_REWARD.png'})
RANKING_RECEIVE = Button(area={'zh-cn': (298, 813, 424, 831)}, color={'zh-cn': (80, 79, 79)}, button={'zh-cn': (298, 813, 424, 831)}, file={'zh-cn': './assets/zh-cn/reward/RANKING_RECEIVE.png'})
RANKING_RED_POINT_CHECK = Button(area={'zh-cn': (675, 179, 694, 198)}, color={'zh-cn': (152, 98, 80)}, button={'zh-cn': (675, 179, 694, 198)}, file={'zh-cn': './assets/zh-cn/reward/RANKING_RED_POINT_CHECK.png'})
RANKING_REWARD = Button(area={'zh-cn': (550, 1195, 579, 1222)}, color={'zh-cn': (90, 191, 239)}, button={'zh-cn': (550, 1195, 579, 1222)}, file={'zh-cn': './assets/zh-cn/reward/RANKING_REWARD.png'})
RECEIVE = Button(area={'zh-cn': (426, 1047, 471, 1090)}, color={'zh-cn': (67, 191, 249)}, button={'zh-cn': (426, 1047, 471, 1090)}, file={'zh-cn': './assets/zh-cn/reward/RECEIVE.png'})
RECEIVE_SPECIAL_ARENA_POINT = Button(area={'zh-cn': (296, 299, 310, 332)}, color={'zh-cn': (174, 206, 151)}, button={'zh-cn': (296, 299, 310, 332)}, file={'zh-cn': './assets/zh-cn/reward/RECEIVE_SPECIAL_ARENA_POINT.png'})
REWARD = Button(area={'zh-cn': (445, 1125, 541, 1150)}, color={'zh-cn': (128, 198, 233)}, button={'zh-cn': (445, 1125, 541, 1150)}, file={'zh-cn': './assets/zh-cn/reward/REWARD.png'})
REWARD_B = Button(area={'zh-cn': (477, 1122, 532, 1152)}, color={'zh-cn': (91, 185, 232)}, button={'zh-cn': (477, 1122, 532, 1152)}, file={'zh-cn': './assets/zh-cn/reward/REWARD_B.png'})
SEND_AND_RECEIVE = Button(area={'zh-cn': (508, 1075, 589, 1101)}, color={'zh-cn': (129, 213, 251)}, button={'zh-cn': (508, 1075, 589, 1101)}, file={'zh-cn': './assets/zh-cn/reward/SEND_AND_RECEIVE.png'})
