from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CLAIM = Button(area={'zh-cn': (487, 1060, 516, 1090)}, color={'zh-cn': (73, 197, 255)}, button={'zh-cn': (487, 1060, 516, 1090)}, file={'zh-cn': './assets/zh-cn/commission/CLAIM.png'})
DISPATCH = Button(area={'zh-cn': (290, 1066, 425, 1086)}, color={'zh-cn': (120, 212, 252)}, button={'zh-cn': (290, 1066, 425, 1086)}, file={'zh-cn': './assets/zh-cn/commission/DISPATCH.png'})
DISPATCH_CONFIRM = Button(area={'zh-cn': (383, 1058, 504, 1095)}, color={'zh-cn': (70, 196, 255)}, button={'zh-cn': (383, 1058, 504, 1095)}, file={'zh-cn': './assets/zh-cn/commission/DISPATCH_CONFIRM.png'})
