import os

import imageio
import numpy as np
from tqdm.contrib.concurrent import process_map

from module.base.utils import get_bbox, get_color, image_size, load_image
from module.config.config import NikkeConfig
from module.config.language import VALID_LANGUAGE
from module.logger import logger

MODULE_FOLDER = './module'
BUTTON_FILE = 'assets.py'
IMPORT_EXP = """
from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.
"""
IMPORT_EXP = IMPORT_EXP.strip().split('\n') + ['']


class ImageExtractor:
    def __init__(self, module, file):
        """
        Args:
            module(str): relative path under assets/zh-CN, e.g. 'event_minigame/event_20250924'
            file(str): filename, e.g. 'GET_MISSION.png'
        """
        self.module = module
        self.name, self.ext = os.path.splitext(file)
        self.area, self.color, self.button, self.file = {}, {}, {}, {}
        for language in VALID_LANGUAGE:
            self.load(language)

    def get_file(self, genre='', language='zh-CN'):
        names = [f'{self.name}.{genre}{ext}' if genre else f'{self.name}{ext}' for ext in ['.png', '.gif']]
        base_dir = os.path.join(NikkeConfig.ASSETS_FOLDER, language, self.module).replace('\\', '/')

        # 1) base_dir 下查找
        for fname in names:
            candidate = os.path.join(base_dir, fname).replace('\\', '/')
            if os.path.exists(candidate):
                return candidate

        # 2) base_dir 一级子目录查找
        if os.path.isdir(base_dir):
            for sub in sorted(os.listdir(base_dir)):
                subpath = os.path.join(base_dir, sub).replace('\\', '/')
                if not os.path.isdir(subpath):
                    continue
                for fname in names:
                    candidate = os.path.join(subpath, fname).replace('\\', '/')
                    if os.path.exists(candidate):
                        return candidate

        # 3) fallback 返回 base_dir 下默认 png
        return os.path.join(base_dir, f'{self.name}.png')

    def extract(self, file):
        if os.path.splitext(file)[1] == '.gif':
            # In a gif Button, use the first image.
            bbox = None
            mean = None
            for image in imageio.mimread(file):
                image = image[:, :, :3] if len(image.shape) == 3 else image
                new_bbox, new_mean = self._extract(image, file)
                if bbox is None:
                    bbox = new_bbox
                elif bbox != new_bbox:
                    logger.warning(f'{file} has multiple different bbox, this will cause unexpected behaviour')
                if mean is None:
                    mean = new_mean
            return bbox, mean
        else:
            image = load_image(file)
            return self._extract(image, file)

    @staticmethod
    def _extract(image, file):
        size = image_size(image)
        if size != (720, 1280):
            logger.warning(f'{file} has wrong resolution: {size}')
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        mean = tuple(np.rint(mean).astype(int))
        return bbox, mean

    def load(self, language='zh-CN'):
        file = self.get_file(language=language)
        if os.path.exists(file):
            area, color = self.extract(file)
            button = area

            for suffix, attr in [('AREA', 'area'), ('COLOR', 'color'), ('BUTTON', 'button')]:
                override_file = self.get_file(suffix, language=language)
                if os.path.exists(override_file):
                    a, c = self.extract(override_file)
                    if attr == 'area':
                        area = a
                    elif attr == 'color':
                        color = c
                    elif attr == 'button':
                        button = a

            self.area[language] = area
            self.color[language] = color
            self.button[language] = button
            self.file[language] = file
        else:
            logger.attr(language, f'{self.name} not found, use zh-CN language assets')
            self.area[language] = self.area['zh-CN']
            self.color[language] = self.color['zh-CN']
            self.button[language] = self.button['zh-CN']
            self.file[language] = self.file['zh-CN']

    @property
    def expression(self):
        return '%s = Button(area=%s, color=%s, button=%s, file=%s)' % (
            self.name, self.area, self.color, self.button, self.file)


class TemplateExtractor(ImageExtractor):
    # def __init__(self, module, file, config):
    #     """
    #     Args:
    #         module(str):
    #         file(str): xxx.png
    #         config(NikkeConfig):
    #     """
    #     self.module = module
    #     self.file = file
    #     self.config = config

    @staticmethod
    def extract(file):
        image = load_image(file)
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        mean = tuple(np.rint(mean).astype(int))
        return bbox, mean

    @property
    def expression(self):
        return '%s = Template(file=%s)' % (self.name, self.file)
        # return '%s = Template(area=%s, color=%s, button=%s, file=\'%s\')' % (
        #     self.name, self.area, self.color, self.button,
        #     self.config.ASSETS_FOLDER + '/' + self.module + '/' + self.name + '.png')


class ModuleExtractor:
    def __init__(self, name, subfolder=None):
        self.name = name
        self.subfolder = subfolder
        if subfolder:
            self.folder = os.path.join(NikkeConfig.ASSETS_FOLDER, 'zh-CN', name, subfolder)
            self.module_path = os.path.join(name, subfolder).replace('\\', '/')
        else:
            self.folder = os.path.join(NikkeConfig.ASSETS_FOLDER, 'zh-CN', name)
            self.module_path = name

    @staticmethod
    def split(file):
        name, ext = os.path.splitext(file)
        name, sub = os.path.splitext(name)
        return name, sub, ext

    def is_base_image(self, file):
        _, sub, _ = self.split(file)
        return sub == ''

    @property
    def expression(self):
        exp = []
        for file in os.listdir(self.folder):
            if file[0].isdigit():
                continue
            if file.startswith('TEMPLATE_'):
                exp.append(TemplateExtractor(module=self.module_path, file=file).expression)
                continue
            if self.is_base_image(file):
                exp.append(ImageExtractor(module=self.module_path, file=file).expression)
                continue

        logger.info('Module: %s(%s)' % (self.folder, len(exp)))
        return IMPORT_EXP + exp

    def write(self):
        folder = os.path.join(MODULE_FOLDER, self.name)
        filename = BUTTON_FILE
        if self.name in ['event_dated', 'event_minigame'] and self.subfolder:
            folder = os.path.join(MODULE_FOLDER, 'event', self.subfolder)
            filename = 'assets_game.py' if self.name == 'event_minigame' else 'assets.py'

        os.makedirs(folder, exist_ok=True)
        with open(os.path.join(folder, filename), 'w', newline='') as f:
            for text in self.expression:
                f.write(text + '\n')


def worker(module):
    folder_path = os.path.join(NikkeConfig.ASSETS_FOLDER, 'zh-CN', module)
    subfolders = [
        f for f in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, f)) and f.startswith('event_')
    ]
    if subfolders:
        for sub in subfolders:
            me = ModuleExtractor(name=module, subfolder=sub)
            me.write()
    else:
        me = ModuleExtractor(name=module)
        me.write()


class AssetExtractor:
    """
    Extract Asset to asset.py.
    All the filename of assets should be in uppercase.

    Asset name starts with digit will ignore.
        E.g. 2020XXXX.png.
    Asset name starts with 'TEMPLATE_' will treat as template.
        E.g. TEMPLATE_AMBUSH_EVADE_SUCCESS.png
             > TEMPLATE_AMBUSH_EVADE_SUCCESS = Template(file='./assets/handler/TEMPLATE_AMBUSH_EVADE_SUCCESS.png')
    Asset name starts other will treat as button.
        E.g. GET_MISSION.png
             > Button(area=(553, 482, 727, 539), color=(93, 142, 203), button=(553, 482, 727, 539), name='GET_MISSION')
    Asset name like XXX.AREA.png, XXX.COLOR.png, XXX.BUTTON.png, will overwrite the attribute of XXX.png.
        E.g. BATTLE_STATUS_S.BUTTON.png overwrites the attribute 'button' of BATTLE_STATUS_S
    Asset name starts with 'OCR_' will treat as button.
        E.g. OCR_EXERCISE_TIMES.png.
    """

    def __init__(self):
        logger.info('Assets extract')
        modules = [
            m
            for m in os.listdir(os.path.join(NikkeConfig.ASSETS_FOLDER, 'zh-CN'))
            if os.path.isdir(os.path.join(NikkeConfig.ASSETS_FOLDER, 'zh-CN', m))
        ]
        process_map(worker, modules)


if __name__ == '__main__':
    ae = AssetExtractor()
