from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ABANDON = Button(area={'zh-CN': (139, 1164, 165, 1194)}, color={'zh-CN': (146, 145, 146)}, button={'zh-CN': (139, 1164, 165, 1194)}, file={'zh-CN': './assets/zh-CN/tribe_tower/ABANDON.png'})
BACK = Button(area={'zh-CN': (33, 1171, 70, 1206)}, color={'zh-CN': (78, 80, 78)}, button={'zh-CN': (33, 1171, 70, 1206)}, file={'zh-CN': './assets/zh-CN/tribe_tower/BACK.png'})
ELYSION_CHECK = Button(area={'zh-CN': (59, 996, 113, 1086)}, color={'zh-CN': (50, 74, 85)}, button={'zh-CN': (59, 996, 113, 1086)}, file={'zh-CN': './assets/zh-CN/tribe_tower/ELYSION_CHECK.png'})
END_CHECK = Button(area={'zh-CN': (261, 1118, 459, 1137)}, color={'zh-CN': (86, 86, 86)}, button={'zh-CN': (261, 1118, 459, 1137)}, file={'zh-CN': './assets/zh-CN/tribe_tower/END_CHECK.png'})
FIGHT = Button(area={'zh-CN': (489, 1158, 611, 1187)}, color={'zh-CN': (135, 179, 220)}, button={'zh-CN': (489, 1158, 611, 1187)}, file={'zh-CN': './assets/zh-CN/tribe_tower/FIGHT.png'})
MISSILIS_CHECK = Button(area={'zh-CN': (223, 996, 278, 1086)}, color={'zh-CN': (50, 75, 87)}, button={'zh-CN': (223, 996, 278, 1086)}, file={'zh-CN': './assets/zh-CN/tribe_tower/MISSILIS_CHECK.png'})
NEXT_STAGE = Button(area={'zh-CN': (552, 1196, 647, 1218)}, color={'zh-CN': (73, 190, 255)}, button={'zh-CN': (552, 1196, 647, 1218)}, file={'zh-CN': './assets/zh-CN/tribe_tower/NEXT_STAGE.png'})
OPERATION_FAILED = Button(area={'zh-CN': (102, 414, 613, 455)}, color={'zh-CN': (75, 7, 6)}, button={'zh-CN': (102, 414, 613, 455)}, file={'zh-CN': './assets/zh-CN/tribe_tower/OPERATION_FAILED.png'})
OPPORTUNITY_0 = Button(area={'zh-CN': (0, 0, 52, 19)}, color={'zh-CN': (38, 58, 58)}, button={'zh-CN': (0, 0, 52, 19)}, file={'zh-CN': './assets/zh-CN/tribe_tower/OPPORTUNITY_0.png'})
OPPORTUNITY_1 = Button(area={'zh-CN': (0, 0, 51, 20)}, color={'zh-CN': (38, 54, 51)}, button={'zh-CN': (0, 0, 51, 20)}, file={'zh-CN': './assets/zh-CN/tribe_tower/OPPORTUNITY_1.png'})
OPPORTUNITY_2 = Button(area={'zh-CN': (0, 0, 52, 19)}, color={'zh-CN': (39, 56, 55)}, button={'zh-CN': (0, 0, 52, 19)}, file={'zh-CN': './assets/zh-CN/tribe_tower/OPPORTUNITY_2.png'})
OPPORTUNITY_3 = Button(area={'zh-CN': (0, 0, 52, 19)}, color={'zh-CN': (39, 57, 55)}, button={'zh-CN': (0, 0, 52, 19)}, file={'zh-CN': './assets/zh-CN/tribe_tower/OPPORTUNITY_3.png'})
PILGRIM_CHECK = Button(area={'zh-CN': (554, 996, 608, 1087)}, color={'zh-CN': (55, 76, 85)}, button={'zh-CN': (554, 996, 608, 1087)}, file={'zh-CN': './assets/zh-CN/tribe_tower/PILGRIM_CHECK.png'})
STAGE_INFO_CHECK = Button(area={'zh-CN': (85, 693, 173, 737)}, color={'zh-CN': (158, 158, 158)}, button={'zh-CN': (85, 693, 173, 737)}, file={'zh-CN': './assets/zh-CN/tribe_tower/STAGE_INFO_CHECK.png'})
TETRA_CHECK = Button(area={'zh-CN': (397, 996, 436, 1087)}, color={'zh-CN': (51, 74, 84)}, button={'zh-CN': (397, 996, 436, 1087)}, file={'zh-CN': './assets/zh-CN/tribe_tower/TETRA_CHECK.png'})
TRIBE_CHECK = Button(area={'zh-CN': (494, 488, 636, 547)}, color={'zh-CN': (186, 226, 244)}, button={'zh-CN': (494, 488, 636, 547)}, file={'zh-CN': './assets/zh-CN/tribe_tower/TRIBE_CHECK.png'})
TRIBE_TOWER_DETAILED_CHECK = Button(area={'zh-CN': (199, 526, 240, 544)}, color={'zh-CN': (84, 85, 84)}, button={'zh-CN': (199, 526, 240, 544)}, file={'zh-CN': './assets/zh-CN/tribe_tower/TRIBE_TOWER_DETAILED_CHECK.png'})
