from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/event_button_extract.py.
# Don't modify it manually.

MINI_GAME = Button(area={'zh-cn': (505, 934, 527, 949)}, color={'zh-cn': (165, 163, 158)}, button={'zh-cn': (505, 934, 527, 949)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME.png'})
MINI_GAME_BACK = Button(area={'zh-cn': (252, 993, 299, 1016)}, color={'zh-cn': (170, 168, 164)}, button={'zh-cn': (252, 993, 299, 1016)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_BACK.png'})
MINI_GAME_BACK_CONFIRM = Button(area={'zh-cn': (507, 789, 555, 812)}, color={'zh-cn': (109, 196, 236)}, button={'zh-cn': (507, 789, 555, 812)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_BACK_CONFIRM.png'})
MINI_GAME_CHECK = Button(area={'zh-cn': (335, 286, 384, 317)}, color={'zh-cn': (53, 4, 2)}, button={'zh-cn': (335, 286, 384, 317)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_CHECK.png'})
MINI_GAME_CLOSE = Button(area={'zh-cn': (632, 181, 672, 222)}, color={'zh-cn': (126, 126, 126)}, button={'zh-cn': (632, 181, 672, 222)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_CLOSE.png'})
MINI_GAME_EXEC_1X = Button(area={'zh-cn': (585, 66, 610, 79)}, color={'zh-cn': (137, 135, 131)}, button={'zh-cn': (585, 66, 610, 79)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_EXEC_1X.png'})
MINI_GAME_EXEC_2X = Button(area={'zh-cn': (582, 66, 611, 79)}, color={'zh-cn': (135, 133, 129)}, button={'zh-cn': (582, 66, 611, 79)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_EXEC_2X.png'})
MINI_GAME_EXEC_BAG = Button(area={'zh-cn': (217, 595, 247, 626)}, color={'zh-cn': (70, 68, 61)}, button={'zh-cn': (217, 595, 247, 626)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_EXEC_BAG.png'})
MINI_GAME_EXEC_BAG_DONE = Button(area={'zh-cn': (471, 955, 516, 977)}, color={'zh-cn': (145, 147, 147)}, button={'zh-cn': (471, 955, 516, 977)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_EXEC_BAG_DONE.png'})
MINI_GAME_EXEC_BUFF_1 = Button(area={'zh-cn': (41, 470, 77, 502)}, color={'zh-cn': (78, 78, 74)}, button={'zh-cn': (41, 470, 77, 502)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_EXEC_BUFF_1.png'})
MINI_GAME_EXEC_BUFF_CHECK = Button(area={'zh-cn': (362, 316, 430, 348)}, color={'zh-cn': (172, 174, 163)}, button={'zh-cn': (362, 316, 430, 348)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_EXEC_BUFF_CHECK.png'})
MINI_GAME_EXEC_BUFF_SELECT = Button(area={'zh-cn': (337, 1041, 382, 1064)}, color={'zh-cn': (163, 164, 162)}, button={'zh-cn': (337, 1041, 382, 1064)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_EXEC_BUFF_SELECT.png'})
MINI_GAME_EXEC_CHECK = Button(area={'zh-cn': (655, 50, 683, 85)}, color={'zh-cn': (204, 203, 198)}, button={'zh-cn': (655, 50, 683, 85)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_EXEC_CHECK.png'})
MINI_GAME_EXEC_CLOSE = Button(area={'zh-cn': (562, 216, 591, 250)}, color={'zh-cn': (172, 176, 170)}, button={'zh-cn': (562, 216, 591, 250)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_EXEC_CLOSE.png'})
MINI_GAME_MAIN_BACK = Button(area={'zh-cn': (70, 1197, 117, 1220)}, color={'zh-cn': (163, 160, 156)}, button={'zh-cn': (70, 1197, 117, 1220)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_MAIN_BACK.png'})
MINI_GAME_MISSION = Button(area={'zh-cn': (494, 1192, 519, 1207)}, color={'zh-cn': (208, 208, 206)}, button={'zh-cn': (494, 1192, 519, 1207)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_MISSION.png'})
MINI_GAME_MISSION_CHECK = Button(area={'zh-cn': (327, 171, 392, 199)}, color={'zh-cn': (179, 183, 176)}, button={'zh-cn': (327, 171, 392, 199)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_MISSION_CHECK.png'})
MINI_GAME_MISSION_CLOSE = Button(area={'zh-cn': (621, 166, 647, 199)}, color={'zh-cn': (182, 187, 180)}, button={'zh-cn': (621, 166, 647, 199)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_MISSION_CLOSE.png'})
MINI_GAME_MISSION_DONE = Button(area={'zh-cn': (262, 1090, 452, 1105)}, color={'zh-cn': (92, 92, 92)}, button={'zh-cn': (262, 1090, 452, 1105)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_MISSION_DONE.png'})
MINI_GAME_MISSION_REWARD = Button(area={'zh-cn': (260, 1090, 451, 1106)}, color={'zh-cn': (89, 96, 103)}, button={'zh-cn': (260, 1090, 451, 1106)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_MISSION_REWARD.png'})
MINI_GAME_REWARD = Button(area={'zh-cn': (306, 732, 413, 751)}, color={'zh-cn': (171, 137, 59)}, button={'zh-cn': (306, 732, 413, 751)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_REWARD.png'})
MINI_GAME_REWARD_DONE = Button(area={'zh-cn': (129, 1058, 167, 1077)}, color={'zh-cn': (21, 116, 132)}, button={'zh-cn': (129, 1058, 167, 1077)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_REWARD_DONE.png'})
MINI_GAME_SHOP_START = Button(area={'zh-cn': (361, 1192, 407, 1214)}, color={'zh-cn': (211, 153, 149)}, button={'zh-cn': (361, 1192, 407, 1214)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_SHOP_START.png'})
MINI_GAME_START = Button(area={'zh-cn': (392, 830, 457, 856)}, color={'zh-cn': (217, 135, 132)}, button={'zh-cn': (392, 830, 457, 856)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_START.png'})
MINI_GAME_START_CONFIRM = Button(area={'zh-cn': (381, 1045, 440, 1070)}, color={'zh-cn': (219, 139, 137)}, button={'zh-cn': (381, 1045, 440, 1070)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_START_CONFIRM.png'})
MINI_GAME_TOUCH = Button(area={'zh-cn': (368, 795, 526, 824)}, color={'zh-cn': (122, 89, 89)}, button={'zh-cn': (368, 795, 526, 824)}, file={'zh-cn': './assets/minigame/event_20250924/MINI_GAME_TOUCH.png'})
