from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ENEMY_DEFEATED = Button(area={'zh-cn': (357, 316, 475, 359)}, color={'zh-cn': (136, 138, 138)}, button={'zh-cn': (357, 316, 475, 359)}, file={'zh-cn': './assets/zh-cn/union_raid/ENEMY_DEFEATED.png'})
ENEMY_DEFEATED_CONFIRM = Button(area={'zh-cn': (263, 911, 293, 932)}, color={'zh-cn': (77, 193, 246)}, button={'zh-cn': (263, 911, 293, 932)}, file={'zh-cn': './assets/zh-cn/union_raid/ENEMY_DEFEATED_CONFIRM.png'})
ENEMY_DEFEATED_CONFIRM_SKIP = Button(area={'zh-cn': (400, 914, 427, 932)}, color={'zh-cn': (231, 186, 146)}, button={'zh-cn': (400, 914, 427, 932)}, file={'zh-cn': './assets/zh-cn/union_raid/ENEMY_DEFEATED_CONFIRM_SKIP.png'})
ENTER_FIGHT = Button(area={'zh-cn': (493, 1181, 604, 1208)}, color={'zh-cn': (242, 135, 118)}, button={'zh-cn': (493, 1181, 604, 1208)}, file={'zh-cn': './assets/zh-cn/union_raid/ENTER_FIGHT.png'})
ENTER_FIGHT_DISABLE = Button(area={'zh-cn': (454, 1183, 521, 1209)}, color={'zh-cn': (47, 51, 50)}, button={'zh-cn': (454, 1183, 521, 1209)}, file={'zh-cn': './assets/zh-cn/union_raid/ENTER_FIGHT_DISABLE.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'zh-cn': (304, 354, 415, 406)}, color={'zh-cn': (68, 55, 36)}, button={'zh-cn': (304, 354, 415, 406)}, file={'zh-cn': './assets/zh-cn/union_raid/FREE_OPPORTUNITY_CHECK.png'})
RAID_RESULT = Button(area={'zh-cn': (288, 347, 441, 388)}, color={'zh-cn': (141, 143, 143)}, button={'zh-cn': (288, 347, 441, 388)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_RESULT.png'})
RAID_TEAM_1 = Button(area={'zh-cn': (296, 865, 360, 887)}, color={'zh-cn': (78, 78, 82)}, button={'zh-cn': (296, 865, 360, 887)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_1.png'})
RAID_TEAM_2 = Button(area={'zh-cn': (373, 865, 439, 887)}, color={'zh-cn': (80, 82, 86)}, button={'zh-cn': (373, 865, 439, 887)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_2.png'})
RAID_TEAM_3 = Button(area={'zh-cn': (450, 865, 516, 887)}, color={'zh-cn': (80, 81, 85)}, button={'zh-cn': (450, 865, 516, 887)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_3.png'})
RAID_TEAM_4 = Button(area={'zh-cn': (528, 864, 593, 887)}, color={'zh-cn': (81, 81, 85)}, button={'zh-cn': (528, 864, 593, 887)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_4.png'})
RAID_TEAM_5 = Button(area={'zh-cn': (605, 864, 670, 887)}, color={'zh-cn': (83, 82, 86)}, button={'zh-cn': (605, 864, 670, 887)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_5.png'})
UNION = Button(area={'zh-cn': (635, 397, 684, 422)}, color={'zh-cn': (97, 99, 103)}, button={'zh-cn': (635, 397, 684, 422)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION.png'})
UNION_CHECK = Button(area={'zh-cn': (527, 1068, 620, 1089)}, color={'zh-cn': (154, 154, 155)}, button={'zh-cn': (527, 1068, 620, 1089)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_CHECK.png'})
UNION_RAID = Button(area={'zh-cn': (298, 898, 421, 914)}, color={'zh-cn': (76, 75, 72)}, button={'zh-cn': (298, 898, 421, 914)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_RAID.png'})
UNION_RAID_CHECK = Button(area={'zh-cn': (310, 358, 409, 374)}, color={'zh-cn': (123, 95, 65)}, button={'zh-cn': (310, 358, 409, 374)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_RAID_CHECK.png'})
UNION_RAID_ENEMY_CHECK = Button(area={'zh-cn': (594, 736, 663, 753)}, color={'zh-cn': (185, 184, 185)}, button={'zh-cn': (594, 736, 663, 753)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_RAID_ENEMY_CHECK.png'})
UNION_RAID_SELECT = Button(area={'zh-cn': (207, 955, 224, 967)}, color={'zh-cn': (66, 45, 32)}, button={'zh-cn': (207, 955, 224, 967)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_RAID_SELECT.png'})
