from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ENEMY_DEFEATED = Button(area={'zh-cn': (357, 316, 475, 359)}, color={'zh-cn': (136, 138, 138)}, button={'zh-cn': (357, 316, 475, 359)}, file={'zh-cn': './assets/zh-cn/union_raid/ENEMY_DEFEATED.png'})
ENEMY_DEFEATED_CONFIRM = Button(area={'zh-cn': (263, 911, 293, 932)}, color={'zh-cn': (77, 193, 246)}, button={'zh-cn': (263, 911, 293, 932)}, file={'zh-cn': './assets/zh-cn/union_raid/ENEMY_DEFEATED_CONFIRM.png'})
ENEMY_DEFEATED_CONFIRM_SKIP = Button(area={'zh-cn': (400, 914, 427, 932)}, color={'zh-cn': (231, 186, 146)}, button={'zh-cn': (400, 914, 427, 932)}, file={'zh-cn': './assets/zh-cn/union_raid/ENEMY_DEFEATED_CONFIRM_SKIP.png'})
ENTER_FIGHT = Button(area={'zh-cn': (493, 1181, 604, 1208)}, color={'zh-cn': (242, 135, 118)}, button={'zh-cn': (493, 1181, 604, 1208)}, file={'zh-cn': './assets/zh-cn/union_raid/ENTER_FIGHT.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'zh-cn': (304, 354, 415, 406)}, color={'zh-cn': (68, 55, 36)}, button={'zh-cn': (304, 354, 415, 406)}, file={'zh-cn': './assets/zh-cn/union_raid/FREE_OPPORTUNITY_CHECK.png'})
RAID_RESULT = Button(area={'zh-cn': (288, 347, 441, 388)}, color={'zh-cn': (141, 143, 143)}, button={'zh-cn': (288, 347, 441, 388)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_RESULT.png'})
RAID_TEAM_1_SELECTED = Button(area={'zh-cn': (307, 866, 349, 886)}, color={'zh-cn': (61, 188, 247)}, button={'zh-cn': (307, 866, 349, 886)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_1_SELECTED.png'})
RAID_TEAM_2 = Button(area={'zh-cn': (396, 865, 415, 887)}, color={'zh-cn': (152, 153, 154)}, button={'zh-cn': (396, 865, 415, 887)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_2.png'})
RAID_TEAM_2_SELECTED = Button(area={'zh-cn': (383, 866, 426, 887)}, color={'zh-cn': (69, 191, 247)}, button={'zh-cn': (383, 866, 426, 887)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_2_SELECTED.png'})
RAID_TEAM_3 = Button(area={'zh-cn': (474, 865, 492, 887)}, color={'zh-cn': (155, 156, 158)}, button={'zh-cn': (474, 865, 492, 887)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_3.png'})
RAID_TEAM_3_SELECTED = Button(area={'zh-cn': (463, 865, 501, 886)}, color={'zh-cn': (73, 192, 247)}, button={'zh-cn': (463, 865, 501, 886)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_3_SELECTED.png'})
RAID_TEAM_4 = Button(area={'zh-cn': (548, 862, 573, 890)}, color={'zh-cn': (113, 113, 115)}, button={'zh-cn': (548, 862, 573, 890)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_4.png'})
RAID_TEAM_4_SELECTED = Button(area={'zh-cn': (542, 866, 578, 886)}, color={'zh-cn': (81, 196, 248)}, button={'zh-cn': (542, 866, 578, 886)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_4_SELECTED.png'})
RAID_TEAM_5 = Button(area={'zh-cn': (626, 864, 649, 888)}, color={'zh-cn': (131, 131, 133)}, button={'zh-cn': (626, 864, 649, 888)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_5.png'})
RAID_TEAM_LOCKED = Button(area={'zh-cn': (361, 978, 396, 994)}, color={'zh-cn': (177, 176, 179)}, button={'zh-cn': (361, 978, 396, 994)}, file={'zh-cn': './assets/zh-cn/union_raid/RAID_TEAM_LOCKED.png'})
UNION = Button(area={'zh-cn': (635, 397, 684, 422)}, color={'zh-cn': (97, 99, 103)}, button={'zh-cn': (635, 397, 684, 422)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION.png'})
UNION_CHECK = Button(area={'zh-cn': (527, 1068, 620, 1089)}, color={'zh-cn': (154, 154, 155)}, button={'zh-cn': (527, 1068, 620, 1089)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_CHECK.png'})
UNION_RAID = Button(area={'zh-cn': (298, 898, 421, 914)}, color={'zh-cn': (76, 75, 72)}, button={'zh-cn': (298, 898, 421, 914)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_RAID.png'})
UNION_RAID_CHECK = Button(area={'zh-cn': (310, 358, 409, 374)}, color={'zh-cn': (123, 95, 65)}, button={'zh-cn': (310, 358, 409, 374)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_RAID_CHECK.png'})
UNION_RAID_ENEMY_CHECK = Button(area={'zh-cn': (594, 736, 663, 753)}, color={'zh-cn': (185, 184, 185)}, button={'zh-cn': (594, 736, 663, 753)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_RAID_ENEMY_CHECK.png'})
UNION_RAID_SELECT = Button(area={'zh-cn': (207, 955, 224, 967)}, color={'zh-cn': (66, 45, 32)}, button={'zh-cn': (207, 955, 224, 967)}, file={'zh-cn': './assets/zh-cn/union_raid/UNION_RAID_SELECT.png'})
