from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CHAMPION = Button(area={'zh-cn': (582, 947, 613, 963)}, color={'zh-cn': (157, 105, 215)}, button={'zh-cn': (582, 947, 613, 963)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHAMPION.png'})
CHAMPION_CHECK = Button(area={'zh-cn': (272, 108, 448, 125)}, color={'zh-cn': (112, 99, 149)}, button={'zh-cn': (272, 108, 448, 125)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHAMPION_CHECK.png'})
CHEER_CANCEL = Button(area={'zh-cn': (245, 1094, 292, 1116)}, color={'zh-cn': (155, 156, 156)}, button={'zh-cn': (245, 1094, 292, 1116)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHEER_CANCEL.png'})
CHEER_CHECK = Button(area={'zh-cn': (337, 194, 387, 218)}, color={'zh-cn': (160, 199, 240)}, button={'zh-cn': (337, 194, 387, 218)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHEER_CHECK.png'})
CHEER_CONFIRM = Button(area={'zh-cn': (471, 1094, 516, 1116)}, color={'zh-cn': (142, 204, 232)}, button={'zh-cn': (471, 1094, 516, 1116)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHEER_CONFIRM.png'})
CHEER_COUNT = Button(area={'zh-cn': (98, 583, 122, 600)}, color={'zh-cn': (238, 200, 192)}, button={'zh-cn': (98, 583, 122, 600)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHEER_COUNT.png'})
CHEER_ENABLE = Button(area={'zh-cn': (474, 1113, 490, 1140)}, color={'zh-cn': (216, 145, 74)}, button={'zh-cn': (474, 1113, 490, 1140)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHEER_ENABLE.png'})
CHEER_RESULT = Button(area={'zh-cn': (277, 324, 454, 365)}, color={'zh-cn': (134, 134, 134)}, button={'zh-cn': (277, 324, 454, 365)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHEER_RESULT.png'})
CHEER_RESULT_NEXT = Button(area={'zh-cn': (292, 1011, 427, 1027)}, color={'zh-cn': (69, 69, 69)}, button={'zh-cn': (292, 1011, 427, 1027)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHEER_RESULT_NEXT.png'})
CHEER_SELECT_1 = Button(area={'zh-cn': (206, 638, 244, 657)}, color={'zh-cn': (127, 126, 127)}, button={'zh-cn': (206, 638, 244, 657)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHEER_SELECT_1.png'})
CHEER_SELECT_2 = Button(area={'zh-cn': (505, 639, 542, 657)}, color={'zh-cn': (130, 129, 130)}, button={'zh-cn': (505, 639, 542, 657)}, file={'zh-cn': './assets/zh-cn/champion_arena/CHEER_SELECT_2.png'})
PROGRESS_FIGHTING = Button(area={'zh-cn': (522, 825, 555, 842)}, color={'zh-cn': (41, 60, 84)}, button={'zh-cn': (522, 825, 555, 842)}, file={'zh-cn': './assets/zh-cn/champion_arena/PROGRESS_FIGHTING.png'})
PROGRESS_NEXT_SEASON = Button(area={'zh-cn': (475, 827, 553, 841)}, color={'zh-cn': (45, 67, 96)}, button={'zh-cn': (475, 827, 553, 841)}, file={'zh-cn': './assets/zh-cn/champion_arena/PROGRESS_NEXT_SEASON.png'})
PROGRESS_RESULTING = Button(area={'zh-cn': (464, 826, 527, 840)}, color={'zh-cn': (52, 77, 124)}, button={'zh-cn': (464, 826, 527, 840)}, file={'zh-cn': './assets/zh-cn/champion_arena/PROGRESS_RESULTING.png'})
PROGRESS_TEAM = Button(area={'zh-cn': (291, 1005, 417, 1021)}, color={'zh-cn': (219, 104, 104)}, button={'zh-cn': (291, 1005, 417, 1021)}, file={'zh-cn': './assets/zh-cn/champion_arena/PROGRESS_TEAM.png'})
PROMOTION = Button(area={'zh-cn': (344, 948, 375, 963)}, color={'zh-cn': (160, 109, 216)}, button={'zh-cn': (344, 948, 375, 963)}, file={'zh-cn': './assets/zh-cn/champion_arena/PROMOTION.png'})
PROMOTION_CHECK = Button(area={'zh-cn': (261, 108, 456, 124)}, color={'zh-cn': (133, 115, 193)}, button={'zh-cn': (261, 108, 456, 124)}, file={'zh-cn': './assets/zh-cn/champion_arena/PROMOTION_CHECK.png'})
