from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/event_button_extract.py.
# Don't modify it manually.

MAIN_GOTO_EVENT = Button(area={'cn': (476, 1066, 559, 1099)}, color={'cn': (144, 154, 181)}, button={'cn': (476, 1066, 559, 1099)}, file={'cn': './assets/event/event_20250703s/MAIN_GOTO_EVENT.png'})
