from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/event_button_extract.py.
# Don't modify it manually.

CHALLENGE = Button(area={'cn': (154, 581, 203, 605)}, color={'cn': (129, 191, 213)}, button={'cn': (154, 581, 203, 605)}, file={'cn': './assets/event/event_20250703s/CHALLENGE.png'})
EVENT_CHECK = Button(area={'cn': (417, 1080, 589, 1135)}, color={'cn': (197, 209, 227)}, button={'cn': (417, 1080, 589, 1135)}, file={'cn': './assets/event/event_20250703s/EVENT_CHECK.png'})
MAIN_GOTO_EVENT = Button(area={'cn': (480, 1039, 523, 1070)}, color={'cn': (122, 172, 188)}, button={'cn': (480, 1039, 523, 1070)}, file={'cn': './assets/event/event_20250703s/MAIN_GOTO_EVENT.png'})
RECEIVE = Button(area={'cn': (297, 811, 423, 832)}, color={'cn': (58, 59, 61)}, button={'cn': (297, 811, 423, 832)}, file={'cn': './assets/event/event_20250703s/RECEIVE.png'})
REWARD = Button(area={'cn': (202, 683, 248, 705)}, color={'cn': (130, 191, 213)}, button={'cn': (202, 683, 248, 705)}, file={'cn': './assets/event/event_20250703s/REWARD.png'})
REWARD_CHECK = Button(area={'cn': (185, 113, 597, 156)}, color={'cn': (170, 156, 69)}, button={'cn': (185, 113, 597, 156)}, file={'cn': './assets/event/event_20250703s/REWARD_CHECK.png'})
REWARD_CLOSED = Button(area={'cn': (640, 72, 667, 100)}, color={'cn': (169, 146, 53)}, button={'cn': (640, 72, 667, 100)}, file={'cn': './assets/event/event_20250703s/REWARD_CLOSED.png'})
REWARD_RECEIVE = Button(area={'cn': (568, 1130, 652, 1152)}, color={'cn': (139, 125, 39)}, button={'cn': (568, 1130, 652, 1152)}, file={'cn': './assets/event/event_20250703s/REWARD_RECEIVE.png'})
REWARD_RECEIVE_DONE = Button(area={'cn': (569, 1131, 651, 1152)}, color={'cn': (103, 103, 105)}, button={'cn': (569, 1131, 651, 1152)}, file={'cn': './assets/event/event_20250703s/REWARD_RECEIVE_DONE.png'})
SKIP = Button(area={'cn': (616, 22, 671, 41)}, color={'cn': (133, 134, 133)}, button={'cn': (616, 22, 671, 41)}, file={'cn': './assets/event/event_20250703s/SKIP.png'})
STORY_1_CHECK = Button(area={'cn': (417, 1080, 589, 1135)}, color={'cn': (197, 209, 227)}, button={'cn': (417, 1080, 589, 1135)}, file={'cn': './assets/event/event_20250703s/STORY_1_CHECK.png'})
STORY_1_HARD = Button(area={'cn': (615, 1160, 665, 1233)}, color={'cn': (158, 81, 127)}, button={'cn': (615, 1160, 665, 1233)}, file={'cn': './assets/event/event_20250703s/STORY_1_HARD.png'})
STORY_1_HARD_HIDDEN = Button(area={'cn': (612, 1157, 666, 1238)}, color={'cn': (50, 52, 52)}, button={'cn': (612, 1157, 666, 1238)}, file={'cn': './assets/event/event_20250703s/STORY_1_HARD_HIDDEN.png'})
STORY_1_HARD_LOCKED = Button(area={'cn': (548, 1151, 683, 1169)}, color={'cn': (119, 122, 126)}, button={'cn': (548, 1151, 683, 1169)}, file={'cn': './assets/event/event_20250703s/STORY_1_HARD_LOCKED.png'})
STORY_1_HARD_STAGE_11 = Button(area={'cn': (146, 785, 375, 819)}, color={'cn': (90, 93, 102)}, button={'cn': (146, 785, 375, 819)}, file={'cn': './assets/event/event_20250703s/STORY_1_HARD_STAGE_11.png'})
STORY_1_HARD_UNLOCK = Button(area={'cn': (343, 733, 438, 753)}, color={'cn': (157, 161, 163)}, button={'cn': (343, 733, 438, 753)}, file={'cn': './assets/event/event_20250703s/STORY_1_HARD_UNLOCK.png'})
STORY_1_NORMAL = Button(area={'cn': (445, 1162, 517, 1231)}, color={'cn': (148, 141, 130)}, button={'cn': (445, 1162, 517, 1231)}, file={'cn': './assets/event/event_20250703s/STORY_1_NORMAL.png'})
STORY_1_NORMAL_STAGE_11 = Button(area={'cn': (115, 858, 373, 884)}, color={'cn': (193, 189, 210)}, button={'cn': (115, 858, 373, 884)}, file={'cn': './assets/event/event_20250703s/STORY_1_NORMAL_STAGE_11.png'})
STORY_2_HARD_STAGE_11 = Button(area={'cn': (404, 588, 439, 664)}, color={'cn': (150, 150, 149)}, button={'cn': (404, 588, 439, 664)}, file={'cn': './assets/event/event_20250703s/STORY_2_HARD_STAGE_11.png'})
STORY_2_NORMAL_STAGE_11 = Button(area={'cn': (317, 746, 404, 788)}, color={'cn': (85, 117, 141)}, button={'cn': (317, 746, 404, 788)}, file={'cn': './assets/event/event_20250703s/STORY_2_NORMAL_STAGE_11.png'})
STORY_STAGE_CHECK = Button(area={'cn': (138, 860, 234, 882)}, color={'cn': (177, 177, 177)}, button={'cn': (138, 860, 234, 882)}, file={'cn': './assets/event/event_20250703s/STORY_STAGE_CHECK.png'})
