from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CHALLENGE = Button(area={'zh-CN': (154, 581, 203, 605)}, color={'zh-CN': (129, 191, 213)}, button={'zh-CN': (154, 581, 203, 605)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/CHALLENGE.png'})
EVENT_CHECK = Button(area={'zh-CN': (417, 1080, 589, 1135)}, color={'zh-CN': (197, 209, 227)}, button={'zh-CN': (417, 1080, 589, 1135)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/EVENT_CHECK.png'})
MAIN_GOTO_EVENT = Button(area={'zh-CN': (480, 1039, 523, 1070)}, color={'zh-CN': (122, 172, 188)}, button={'zh-CN': (480, 1039, 523, 1070)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/MAIN_GOTO_EVENT.png'})
RECEIVE = Button(area={'zh-CN': (297, 811, 423, 832)}, color={'zh-CN': (58, 59, 61)}, button={'zh-CN': (297, 811, 423, 832)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/RECEIVE.png'})
REWARD = Button(area={'zh-CN': (202, 683, 248, 705)}, color={'zh-CN': (130, 191, 213)}, button={'zh-CN': (202, 683, 248, 705)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/REWARD.png'})
REWARD_CHECK = Button(area={'zh-CN': (185, 113, 597, 156)}, color={'zh-CN': (170, 156, 69)}, button={'zh-CN': (185, 113, 597, 156)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/REWARD_CHECK.png'})
REWARD_CLOSED = Button(area={'zh-CN': (640, 72, 667, 100)}, color={'zh-CN': (169, 146, 53)}, button={'zh-CN': (640, 72, 667, 100)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/REWARD_CLOSED.png'})
REWARD_RECEIVE = Button(area={'zh-CN': (568, 1130, 652, 1152)}, color={'zh-CN': (139, 125, 39)}, button={'zh-CN': (568, 1130, 652, 1152)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/REWARD_RECEIVE.png'})
REWARD_RECEIVE_DONE = Button(area={'zh-CN': (569, 1131, 651, 1152)}, color={'zh-CN': (103, 103, 105)}, button={'zh-CN': (569, 1131, 651, 1152)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/REWARD_RECEIVE_DONE.png'})
SKIP = Button(area={'zh-CN': (616, 22, 671, 41)}, color={'zh-CN': (133, 134, 133)}, button={'zh-CN': (616, 22, 671, 41)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/SKIP.png'})
STORY_1_CHECK = Button(area={'zh-CN': (417, 1080, 589, 1135)}, color={'zh-CN': (197, 209, 227)}, button={'zh-CN': (417, 1080, 589, 1135)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_1_CHECK.png'})
STORY_1_HARD = Button(area={'zh-CN': (615, 1160, 665, 1233)}, color={'zh-CN': (158, 81, 127)}, button={'zh-CN': (615, 1160, 665, 1233)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_1_HARD.png'})
STORY_1_HARD_HIDDEN = Button(area={'zh-CN': (612, 1157, 666, 1238)}, color={'zh-CN': (50, 52, 52)}, button={'zh-CN': (612, 1157, 666, 1238)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_1_HARD_HIDDEN.png'})
STORY_1_HARD_LOCKED = Button(area={'zh-CN': (548, 1151, 683, 1169)}, color={'zh-CN': (119, 122, 126)}, button={'zh-CN': (548, 1151, 683, 1169)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_1_HARD_LOCKED.png'})
STORY_1_HARD_STAGE_11 = Button(area={'zh-CN': (146, 785, 375, 819)}, color={'zh-CN': (90, 93, 102)}, button={'zh-CN': (146, 785, 375, 819)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_1_HARD_STAGE_11.png'})
STORY_1_HARD_UNLOCK = Button(area={'zh-CN': (343, 733, 438, 753)}, color={'zh-CN': (157, 161, 163)}, button={'zh-CN': (343, 733, 438, 753)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_1_HARD_UNLOCK.png'})
STORY_1_NORMAL = Button(area={'zh-CN': (445, 1162, 517, 1231)}, color={'zh-CN': (148, 141, 130)}, button={'zh-CN': (445, 1162, 517, 1231)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_1_NORMAL.png'})
STORY_1_NORMAL_STAGE_11 = Button(area={'zh-CN': (115, 858, 373, 884)}, color={'zh-CN': (193, 189, 210)}, button={'zh-CN': (115, 858, 373, 884)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_1_NORMAL_STAGE_11.png'})
STORY_2_HARD_STAGE_11 = Button(area={'zh-CN': (404, 588, 439, 664)}, color={'zh-CN': (150, 150, 149)}, button={'zh-CN': (404, 588, 439, 664)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_2_HARD_STAGE_11.png'})
STORY_2_NORMAL_STAGE_11 = Button(area={'zh-CN': (317, 746, 404, 788)}, color={'zh-CN': (85, 117, 141)}, button={'zh-CN': (317, 746, 404, 788)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_2_NORMAL_STAGE_11.png'})
STORY_STAGE_CHECK = Button(area={'zh-CN': (138, 860, 234, 882)}, color={'zh-CN': (177, 177, 177)}, button={'zh-CN': (138, 860, 234, 882)}, file={'zh-CN': './assets/zh-CN/event_dated/event_20250703s/STORY_STAGE_CHECK.png'})
