from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COMPLETED_1 = Button(area={'zh-cn': (496, 834, 529, 852)}, color={'zh-cn': (106, 89, 40)}, button={'zh-cn': (496, 834, 529, 852)}, file={'zh-cn': './assets/zh-cn/liberation/COMPLETED_1.png'})
COMPLETED_2 = Button(area={'zh-cn': (497, 914, 526, 928)}, color={'zh-cn': (104, 46, 146)}, button={'zh-cn': (497, 914, 526, 928)}, file={'zh-cn': './assets/zh-cn/liberation/COMPLETED_2.png'})
COMPLETED_3 = Button(area={'zh-cn': (497, 991, 527, 1007)}, color={'zh-cn': (27, 96, 129)}, button={'zh-cn': (497, 991, 527, 1007)}, file={'zh-cn': './assets/zh-cn/liberation/COMPLETED_3.png'})
COMPLETED_4 = Button(area={'zh-cn': (363, 961, 398, 977)}, color={'zh-cn': (163, 47, 174)}, button={'zh-cn': (363, 961, 398, 977)}, file={'zh-cn': './assets/zh-cn/liberation/COMPLETED_4.png'})
COMPLETED_5 = Button(area={'zh-cn': (361, 1039, 397, 1055)}, color={'zh-cn': (60, 123, 167)}, button={'zh-cn': (361, 1039, 397, 1055)}, file={'zh-cn': './assets/zh-cn/liberation/COMPLETED_5.png'})
COMPLETED_6 = Button(area={'zh-cn': (363, 1115, 395, 1134)}, color={'zh-cn': (196, 128, 44)}, button={'zh-cn': (363, 1115, 395, 1134)}, file={'zh-cn': './assets/zh-cn/liberation/COMPLETED_6.png'})
CONFIRM_D = Button(area={'zh-cn': (330, 1141, 389, 1167)}, color={'zh-cn': (136, 137, 137)}, button={'zh-cn': (330, 1141, 389, 1167)}, file={'zh-cn': './assets/zh-cn/liberation/CONFIRM_D.png'})
