from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ADVANCED_MATERIALS = Button(area={'zh-CN': (204, 607, 269, 672)}, color={'zh-CN': (102, 97, 99)}, button={'zh-CN': (204, 607, 269, 672)}, file={'zh-CN': './assets/zh-CN/daily/ADVANCED_MATERIALS.png'})
COMPLETED_CHECK = Button(area={'zh-CN': (170, 204, 190, 223)}, color={'zh-CN': (116, 111, 140)}, button={'zh-CN': (170, 204, 190, 223)}, file={'zh-CN': './assets/zh-CN/daily/COMPLETED_CHECK.png'})
ENHANCE = Button(area={'zh-CN': (366, 903, 413, 925)}, color={'zh-CN': (26, 110, 155)}, button={'zh-CN': (366, 903, 413, 925)}, file={'zh-CN': './assets/zh-CN/daily/ENHANCE.png'})
ENHANCEMENT_CHECK = Button(area={'zh-CN': (341, 164, 437, 189)}, color={'zh-CN': (137, 188, 244)}, button={'zh-CN': (341, 164, 437, 189)}, file={'zh-CN': './assets/zh-CN/daily/ENHANCEMENT_CHECK.png'})
ENHANCE_CONFIRM = Button(area={'zh-CN': (492, 1065, 550, 1094)}, color={'zh-CN': (77, 199, 255)}, button={'zh-CN': (492, 1065, 550, 1094)}, file={'zh-CN': './assets/zh-CN/daily/ENHANCE_CONFIRM.png'})
GIFT_RANK_R = Button(area={'zh-CN': (454, 648, 490, 673)}, color={'zh-CN': (231, 207, 193)}, button={'zh-CN': (454, 648, 490, 673)}, file={'zh-CN': './assets/zh-CN/daily/GIFT_RANK_R.png'})
GIFT_SELECT_CHECK = Button(area={'zh-CN': (449, 640, 489, 679)}, color={'zh-CN': (240, 248, 252)}, button={'zh-CN': (449, 640, 489, 679)}, file={'zh-CN': './assets/zh-CN/daily/GIFT_SELECT_CHECK.png'})
GIFT_SEND = Button(area={'zh-CN': (499, 1067, 547, 1091)}, color={'zh-CN': (114, 208, 248)}, button={'zh-CN': (499, 1067, 547, 1091)}, file={'zh-CN': './assets/zh-CN/daily/GIFT_SEND.png'})
GIFT_SEND_CLOSE = Button(area={'zh-CN': (638, 165, 668, 194)}, color={'zh-CN': (245, 154, 70)}, button={'zh-CN': (638, 165, 668, 194)}, file={'zh-CN': './assets/zh-CN/daily/GIFT_SEND_CLOSE.png'})
GIFT_SEND_DONE = Button(area={'zh-CN': (498, 1067, 547, 1091)}, color={'zh-CN': (173, 170, 168)}, button={'zh-CN': (498, 1067, 547, 1091)}, file={'zh-CN': './assets/zh-CN/daily/GIFT_SEND_DONE.png'})
GOTO_EQUIPMENT_LIST = Button(area={'zh-CN': (373, 199, 429, 217)}, color={'zh-CN': (152, 153, 155)}, button={'zh-CN': (373, 199, 429, 217)}, file={'zh-CN': './assets/zh-CN/daily/GOTO_EQUIPMENT_LIST.png'})
LU_CHECK = Button(area={'zh-CN': (280, 841, 455, 862)}, color={'zh-CN': (24, 53, 49)}, button={'zh-CN': (280, 841, 455, 862)}, file={'zh-CN': './assets/zh-CN/daily/LU_CHECK.png'})
NORMAL_MATERIALS = Button(area={'zh-CN': (98, 607, 152, 669)}, color={'zh-CN': (113, 108, 109)}, button={'zh-CN': (98, 607, 152, 669)}, file={'zh-CN': './assets/zh-CN/daily/NORMAL_MATERIALS.png'})
NO_ITEMS = Button(area={'zh-CN': (338, 711, 454, 732)}, color={'zh-CN': (188, 186, 186)}, button={'zh-CN': (338, 711, 454, 732)}, file={'zh-CN': './assets/zh-CN/daily/NO_ITEMS.png'})
RANDOM_EQUIPMENT = Button(area={'zh-CN': (110, 343, 136, 352)}, color={'zh-CN': (175, 175, 176)}, button={'zh-CN': (110, 343, 136, 352)}, file={'zh-CN': './assets/zh-CN/daily/RANDOM_EQUIPMENT.png'})
RECEIVE = Button(area={'zh-CN': (533, 1142, 617, 1161)}, color={'zh-CN': (149, 222, 255)}, button={'zh-CN': (533, 1142, 617, 1161)}, file={'zh-CN': './assets/zh-CN/daily/RECEIVE.png'})
SELECT = Button(area={'zh-CN': (296, 1150, 421, 1182)}, color={'zh-CN': (107, 208, 230)}, button={'zh-CN': (296, 1150, 421, 1182)}, file={'zh-CN': './assets/zh-CN/daily/SELECT.png'})
SW = Button(area={'zh-CN': (289, 1156, 444, 1268)}, color={'zh-CN': (117, 138, 152)}, button={'zh-CN': (289, 1156, 444, 1268)}, file={'zh-CN': './assets/zh-CN/daily/SW.png'})
