from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

AGE_20 = Button(area={'zh-cn': (131, 801, 176, 820)}, color={'zh-cn': (207, 207, 207)}, button={'zh-cn': (131, 801, 176, 820)}, file={'zh-cn': './assets/zh-cn/gift/AGE_20.png'})
CONFIRM = Button(area={'zh-cn': (392, 970, 435, 996)}, color={'zh-cn': (64, 182, 237)}, button={'zh-cn': (392, 970, 435, 996)}, file={'zh-cn': './assets/zh-cn/gift/CONFIRM.png'})
CONSUMPTION_RESTRICTIONS = Button(area={'zh-cn': (312, 314, 409, 340)}, color={'zh-cn': (139, 180, 224)}, button={'zh-cn': (312, 314, 409, 340)}, file={'zh-cn': './assets/zh-cn/gift/CONSUMPTION_RESTRICTIONS.png'})
DAILY = Button(area={'zh-cn': (182, 356, 217, 375)}, color={'zh-cn': (199, 199, 206)}, button={'zh-cn': (182, 356, 217, 375)}, file={'zh-cn': './assets/zh-cn/gift/DAILY.png'})
DAILY_CHECK = Button(area={'zh-cn': (181, 356, 218, 375)}, color={'zh-cn': (107, 221, 250)}, button={'zh-cn': (181, 356, 218, 375)}, file={'zh-cn': './assets/zh-cn/gift/DAILY_CHECK.png'})
FAILED_CHECK = Button(area={'zh-cn': (198, 547, 508, 568)}, color={'zh-cn': (174, 174, 174)}, button={'zh-cn': (198, 547, 508, 568)}, file={'zh-cn': './assets/zh-cn/gift/FAILED_CHECK.png'})
GENERAL_GIFT_CHECK = Button(area={'zh-cn': (323, 111, 446, 141)}, color={'zh-cn': (179, 185, 202)}, button={'zh-cn': (323, 111, 446, 141)}, file={'zh-cn': './assets/zh-cn/gift/GENERAL_GIFT_CHECK.png'})
GIFT = Button(area={'zh-cn': (113, 803, 159, 821)}, color={'zh-cn': (157, 159, 161)}, button={'zh-cn': (113, 803, 159, 821)}, file={'zh-cn': './assets/zh-cn/gift/GIFT.png'})
GOTO_GENERAL_GIFT = Button(area={'zh-cn': (132, 261, 173, 306)}, color={'zh-cn': (114, 115, 118)}, button={'zh-cn': (132, 261, 173, 306)}, file={'zh-cn': './assets/zh-cn/gift/GOTO_GENERAL_GIFT.png'})
MONTHLY = Button(area={'zh-cn': (579, 356, 615, 375)}, color={'zh-cn': (199, 198, 207)}, button={'zh-cn': (579, 356, 615, 375)}, file={'zh-cn': './assets/zh-cn/gift/MONTHLY.png'})
MONTHLY_CHECK = Button(area={'zh-cn': (579, 356, 615, 374)}, color={'zh-cn': (114, 224, 250)}, button={'zh-cn': (579, 356, 615, 374)}, file={'zh-cn': './assets/zh-cn/gift/MONTHLY_CHECK.png'})
WEEKLY = Button(area={'zh-cn': (379, 355, 417, 375)}, color={'zh-cn': (198, 198, 206)}, button={'zh-cn': (379, 355, 417, 375)}, file={'zh-cn': './assets/zh-cn/gift/WEEKLY.png'})
WEEKLY_CHECK = Button(area={'zh-cn': (380, 356, 417, 375)}, color={'zh-cn': (116, 224, 251)}, button={'zh-cn': (380, 356, 417, 375)}, file={'zh-cn': './assets/zh-cn/gift/WEEKLY_CHECK.png'})
