from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

AGE_20 = Button(area={'zh-CN': (131, 801, 176, 820)}, color={'zh-CN': (207, 207, 207)}, button={'zh-CN': (131, 801, 176, 820)}, file={'zh-CN': './assets/zh-CN/gift/AGE_20.png'})
CONFIRM = Button(area={'zh-CN': (392, 970, 435, 996)}, color={'zh-CN': (64, 182, 237)}, button={'zh-CN': (392, 970, 435, 996)}, file={'zh-CN': './assets/zh-CN/gift/CONFIRM.png'})
CONSUMPTION_RESTRICTIONS = Button(area={'zh-CN': (312, 314, 409, 340)}, color={'zh-CN': (139, 180, 224)}, button={'zh-CN': (312, 314, 409, 340)}, file={'zh-CN': './assets/zh-CN/gift/CONSUMPTION_RESTRICTIONS.png'})
DAILY = Button(area={'zh-CN': (182, 356, 217, 375)}, color={'zh-CN': (199, 199, 206)}, button={'zh-CN': (182, 356, 217, 375)}, file={'zh-CN': './assets/zh-CN/gift/DAILY.png'})
DAILY_CHECK = Button(area={'zh-CN': (181, 356, 218, 375)}, color={'zh-CN': (107, 221, 250)}, button={'zh-CN': (181, 356, 218, 375)}, file={'zh-CN': './assets/zh-CN/gift/DAILY_CHECK.png'})
FAILED_CHECK = Button(area={'zh-CN': (198, 547, 508, 568)}, color={'zh-CN': (174, 174, 174)}, button={'zh-CN': (198, 547, 508, 568)}, file={'zh-CN': './assets/zh-CN/gift/FAILED_CHECK.png'})
GENERAL_GIFT_CHECK = Button(area={'zh-CN': (323, 111, 446, 141)}, color={'zh-CN': (179, 185, 202)}, button={'zh-CN': (323, 111, 446, 141)}, file={'zh-CN': './assets/zh-CN/gift/GENERAL_GIFT_CHECK.png'})
GIFT = Button(area={'zh-CN': (113, 803, 159, 821)}, color={'zh-CN': (157, 159, 161)}, button={'zh-CN': (113, 803, 159, 821)}, file={'zh-CN': './assets/zh-CN/gift/GIFT.png'})
GIFT_B = Button(area={'zh-CN': (637, 710, 687, 730)}, color={'zh-CN': (200, 205, 230)}, button={'zh-CN': (637, 710, 687, 730)}, file={'zh-CN': './assets/zh-CN/gift/GIFT_B.png'})
GOTO_GENERAL_GIFT = Button(area={'zh-CN': (132, 261, 173, 306)}, color={'zh-CN': (114, 115, 118)}, button={'zh-CN': (132, 261, 173, 306)}, file={'zh-CN': './assets/zh-CN/gift/GOTO_GENERAL_GIFT.png'})
GOTO_STEPUP_GIFT = Button(area={'zh-CN': (137, 276, 157, 307)}, color={'zh-CN': (141, 141, 143)}, button={'zh-CN': (137, 276, 157, 307)}, file={'zh-CN': './assets/zh-CN/gift/GOTO_STEPUP_GIFT.png'})
LIMITED_GIFT_CHECK = Button(area={'zh-CN': (298, 127, 315, 145)}, color={'zh-CN': (162, 171, 189)}, button={'zh-CN': (298, 127, 315, 145)}, file={'zh-CN': './assets/zh-CN/gift/LIMITED_GIFT_CHECK.png'})
MONTHLY = Button(area={'zh-CN': (579, 356, 615, 375)}, color={'zh-CN': (199, 198, 207)}, button={'zh-CN': (579, 356, 615, 375)}, file={'zh-CN': './assets/zh-CN/gift/MONTHLY.png'})
MONTHLY_CHECK = Button(area={'zh-CN': (579, 356, 615, 374)}, color={'zh-CN': (114, 224, 250)}, button={'zh-CN': (579, 356, 615, 374)}, file={'zh-CN': './assets/zh-CN/gift/MONTHLY_CHECK.png'})
STEPUP = Button(area={'zh-CN': (67, 358, 111, 373)}, color={'zh-CN': (194, 196, 204)}, button={'zh-CN': (67, 358, 111, 373)}, file={'zh-CN': './assets/zh-CN/gift/STEPUP.png'})
STEPUP_CHECK = Button(area={'zh-CN': (209, 449, 290, 487)}, color={'zh-CN': (179, 182, 206)}, button={'zh-CN': (209, 449, 290, 487)}, file={'zh-CN': './assets/zh-CN/gift/STEPUP_CHECK.png'})
WEEKLY = Button(area={'zh-CN': (379, 355, 417, 375)}, color={'zh-CN': (198, 198, 206)}, button={'zh-CN': (379, 355, 417, 375)}, file={'zh-CN': './assets/zh-CN/gift/WEEKLY.png'})
WEEKLY_CHECK = Button(area={'zh-CN': (380, 356, 417, 375)}, color={'zh-CN': (116, 224, 251)}, button={'zh-CN': (380, 356, 417, 375)}, file={'zh-CN': './assets/zh-CN/gift/WEEKLY_CHECK.png'})
