import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False
    Scheduler_NextRun = datetime.datetime(1989, 12, 27, 0, 0)
    Scheduler_Command = 'NKAS'
    Scheduler_SuccessInterval = 0
    Scheduler_FailureInterval = 120
    Scheduler_ServerUpdate = '04:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_PackageName = 'com_proximabeta_nikke'  # com_proximabeta_nikke, com_gamamobi_nikke
    Emulator_ScreenshotMethod = 'DroidCast'  # DroidCast
    Emulator_ControlMethod = 'minitouch'  # minitouch
    Emulator_AdbRestart = False
    Emulator_ScreenshotInterval = 0.5

    # Group `Optimization`
    Optimization_AutoRedCircle = False
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game

    # Group `Reward`
    Reward_CollectSocialPoint = True
    Reward_CollectSpecialArenaPoint = True
    Reward_CollectRanking = True

    # Group `DailyRecruit`
    DailyRecruit_EventFreeRecruit = True
    DailyRecruit_SocialPointRecruit = True

    # Group `Area`
    Area_Difficulty = 'Level_1'  # Level_1, Level_2, Level_3, Level_4, Level_5
    Area_OnsetArea = 'A'  # A, B, C
    Area_EndingArea = 'A'  # A, B, C

    # Group `Overcome`
    Overcome_OnlyToCompleteDailyMission = False

    # Group `GeneralShop`
    GeneralShop_enable = True

    # Group `ArenaShop`
    ArenaShop_enable = False
    ArenaShop_priority = None

    # Group `RubbishShop`
    RubbishShop_priority = None

    # Group `Notification`
    Notification_WhenDailyTaskCompleted = False
    Notification_WhenDailyTaskCrashed = False
    Notification_OnePushConfig = 'provider: null'

    # Group `Daily`
    Daily_SendGift = False
    Daily_EnhanceEquipment = False
    Daily_CallReward = False

    # Group `CollectionItems`
    CollectionItems_NIKKE = 'All'  # All, Laplace, Frima, Diesel, Exia

    # Group `OpponentSelection`
    OpponentSelection_Enable = False
    OpponentSelection_SortingWeight = '{"Power":0.3, "CommanderLevel":0.2, "SynchroLevel":0.3, "Ranking":0.2}'
    OpponentSelection_SelectionStrategy = 'Min'  # Max, Middle, Min

    # Group `Conversation`
    Conversation_QuickConsultation = False
    Conversation_OnlyFavourite = False

    # Group `BlaAuth`
    BlaAuth_UserAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'
    BlaAuth_Cookie = None
    BlaAuth_OpenID = None

    # Group `BlaDaily`
    BlaDaily_Enable = False
    BlaDaily_Immediately = False
    BlaDaily_PostID = None
    BlaDaily_CommentID = None
    BlaDaily_Points = None

    # Group `Coop`
    Coop_EventCoop = False
    Coop_MatchDifficulty = 'Normal'  # Normal

    # Group `CDK`
    CDK_Enable = False
    CDK_Source = 'https://gamewith.jp/nikke/article/show/371014'

    # Group `Event`
    Event_Event = ''  # event_20250612
    Event_LoginStamp = True
    Event_Challenge = True
    Event_Story = False
    Event_StoryPart = 'Story_1'  # Story_1, Story_2
    Event_StoryDifficulty = 'Normal'  # Normal, Hard
    Event_Game = False
    Event_Shop = False

    # Group `Storage`
    Storage_Storage = {}
