import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(1989, 12, 27, 0, 0)
    Scheduler_Command = 'NKAS'
    Scheduler_SuccessInterval = 0
    Scheduler_FailureInterval = 120
    Scheduler_ServerUpdate = '05:00'

    # Group `Client`
    Client_Platform = 'adb'  # adb, win
    Client_Language = 'zh-CN'  # zh-CN, en-US

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_PackageName = 'com.proximabeta.nikke'  # com.proximabeta.nikke, com.gamamobi.nikke, com.proximabeta.nikke, com.gamamobi.nikke
    Emulator_ScreenshotMethod = 'DroidCast'  # DroidCast
    Emulator_ControlMethod = 'minitouch'  # minitouch
    Emulator_AdbRestart = False
    Emulator_ScreenshotInterval = 0.5

    # Group `EmulatorInfo`
    EmulatorInfo_Emulator = 'auto'  # auto, NoxPlayer, NoxPlayer64, BlueStacks4, BlueStacks5, BlueStacks4HyperV, BlueStacks5HyperV, LDPlayer3, LDPlayer4, LDPlayer9, MuMuPlayer, MuMuPlayerX, MuMuPlayer12, MEmuPlayer
    EmulatorInfo_name = None
    EmulatorInfo_path = None

    # Group `PCClient`
    PCClient_Screens = False
    PCClient_ScreenNumber = 0  # 0, 1, 2, 3, 4, 5
    PCClient_GameResolutionCompat = True
    PCClient_CloseAutoHdr = True
    PCClient_ScreenRotate = False
    PCClient_GameWindowPosition = 'center'  # center, left, right, topleft, topright
    PCClient_Account = None
    PCClient_Password = None

    # Group `PCClientInfo`
    PCClientInfo_Client = 'intl'  # intl, hmt
    PCClientInfo_AutoFillName = True
    PCClientInfo_LauncherPath = None
    PCClientInfo_LauncherTitleName = None
    PCClientInfo_LauncherProcessName = None
    PCClientInfo_GamePath = None
    PCClientInfo_GameTitleName = None
    PCClientInfo_GameProcessName = None
    PCClientInfo_ScreenshotInterval = 0.3

    # Group `Optimization`
    Optimization_AutoRedCircle = False
    Optimization_OcrModelType = 'mobile'  # mobile, server
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game

    # Group `Reward`
    Reward_CollectSocialPoint = True
    Reward_CollectSpecialArenaPoint = True
    Reward_CollectRanking = True

    # Group `DailyRecruit`
    DailyRecruit_EventFreeRecruit = True
    DailyRecruit_SocialPointRecruit = True

    # Group `SimulationRoom`
    SimulationRoom_QuickSimulation = True
    SimulationRoom_Immediately = False

    # Group `Area`
    Area_Difficulty = 'Level_1'  # Level_1, Level_2, Level_3, Level_4, Level_5
    Area_OnsetArea = 'A'  # A, B, C
    Area_EndingArea = 'A'  # A, B, C

    # Group `Overcome`
    Overcome_OnlyToCompleteDailyMission = False

    # Group `GeneralShop`
    GeneralShop_enable = True
    GeneralShop_priority = 'GRATIS > CORE_DUST_CASE > ORNAMENT'

    # Group `ArenaShop`
    ArenaShop_enable = False
    ArenaShop_priority = None

    # Group `RubbishShop`
    RubbishShop_priority = 'GEM > CORE_DUST_CASE'
    RubbishShop_bonePriority = None

    # Group `Notification`
    Notification_WhenDailyTaskCompleted = False
    Notification_WhenDailyTaskCrashed = False
    Notification_WinOnePush = False
    Notification_OnePushConfig = 'provider: null'

    # Group `Daily`
    Daily_SendGift = False
    Daily_EnhanceEquipment = False
    Daily_CallReward = False

    # Group `CollectionItems`
    CollectionItems_Enable = False
    CollectionItems_Priority = None

    # Group `OpponentSelection`
    OpponentSelection_Enable = False
    OpponentSelection_SortingWeight = '{"Power":0.3, "CommanderLevel":0.2, "SynchroLevel":0.3, "Ranking":0.2}'
    OpponentSelection_SelectionStrategy = 'Min'  # Max, Middle, Min

    # Group `Conversation`
    Conversation_OnlyFavourite = False
    Conversation_OnlyLogsNotMax = False

    # Group `BlaAuth`
    BlaAuth_UserAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'
    BlaAuth_Cookie = None
    BlaAuth_XCommonParams = None

    # Group `BlaDaily`
    BlaDaily_Immediately = False
    BlaDaily_Points = None

    # Group `Coop`
    Coop_MatchDifficulty = 'Normal'  # Normal

    # Group `CDK`
    CDK_Extra = False
    CDK_Source = 'https://gamewith.jp/nikke/article/show/371014'

    # Group `BlaExchange`
    BlaExchange_Priority = 'Gem_×320 > Gem_×120 > Gem_×60 > Gem_×30 > Welcome_Gift_Core_Dust_×30'

    # Group `Event`
    Event_Event = ''  # event_20251030, event_20251016, event_20250924, event_20250904, event_20250807, event_20250716, event_20250703s, event_20250703l, event_20250612
    Event_LoginStamp = True
    Event_Challenge = True
    Event_Story = False
    Event_StoryPart = 'Story_1'  # Story_1, Story_2
    Event_StoryDifficulty = 'Normal'  # Normal, Hard
    Event_Coop = False
    Event_Shop = False
    Event_ShopDelayList = 'TITLE'
    Event_Game = False
    Event_GameStorySkip = False
    Event_GameLoop = False

    # Group `CheerStrategy`
    CheerStrategy_Enable = False
    CheerStrategy_Strategy = 'Most'  # Most, Few, Random

    # Group `Interception`
    Interception_Boss = 'Kraken'  # Kraken, Indivilia, Harvester, MirrorContainer, Ultra
    Interception_AchieveLevel = 1  # 1, 2, 3, 4, 5, 6, 7, 8, 9
    Interception_DropScreenshotPath = None

    # Group `InterceptionTeam`
    InterceptionTeam_Kraken = 1  # 1, 2, 3, 4, 5
    InterceptionTeam_Indivilia = 2  # 1, 2, 3, 4, 5
    InterceptionTeam_Harvester = 3  # 1, 2, 3, 4, 5
    InterceptionTeam_MirrorContainer = 4  # 1, 2, 3, 4, 5
    InterceptionTeam_Ultra = 5  # 1, 2, 3, 4, 5

    # Group `Overclock`
    Overclock_SkipRatioCheck = False
    Overclock_AlwaysReselect = False
    Overclock_ModifierList = 'ENEMY_WEAPON_UP_3\nENEMY_ARMOR_UP_3\nENEMY_VITALS_UP_3\nNO_RECYCLING\nAGGRESSIVE_TACTICS\nRUSH_HOUR_3\nRELEVANT_PERSONNEL_ONLY'

    # Group `AutoTower`
    AutoTower_Enable = True

    # Group `SemiCombat`
    SemiCombat_SkipStory = False
    SemiCombat_FightQuickly = False
    SemiCombat_MainStoryMark = False

    # Group `BlaCDKManual`
    BlaCDKManual_CDK = None

    # Group `Highlights`
    Highlights_AutoSwitch = True

    # Group `ScreenRotate`
    ScreenRotate_Orientation = 0  # 0, 1

    # Group `Synchro`
    Synchro_UseBox = True

    # Group `Hosts`
    Hosts_Action = 'Add'  # Add, Delete
    Hosts_Hosts = '# 通用\n18.155.202.10 cloud.nikke-kr.com\n43.132.85.192 nikke-en.com\n43.132.85.192 nikke-jp.com\n43.132.85.192 nikke-kr.com\n# 国际 Global\n43.152.186.163 global-lobby.nikke-kr.com\n43.152.186.163 global-match.nikke-kr.com\n# 日本 JP\n# 43.152.186.163 jp-lobby.nikke-kr.com\n# 43.152.186.163 jp-match.nikke-kr.com\n# 韩国 KR\n# 43.152.186.163 kr-lobby.nikke-kr.com\n# 43.152.186.163 kr-match.nikke-kr.com\n# 东南亚 SEA\n# 43.152.186.163 sea-lobby.nikke-kr.com\n# 43.152.186.163 sea-match.nikke-kr.com\n# 港澳台 HK/MC/TW\n# 43.152.186.163 hmt-lobby.nikke-kr.com\n# 43.152.186.163 hmt-match.nikke-kr.com\n# 北美 NA\n# 175.97.131.54 us-match.nikke-kr.com\n# 175.97.131.54 us-lobby.nikke-kr.com'

    # Group `Storage`
    Storage_Storage = {}
