from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

END_COMPETITION = Button(area={'zh-CN': (45, 1194, 86, 1236)}, color={'zh-CN': (117, 116, 117)}, button={'zh-CN': (45, 1194, 86, 1236)}, file={'zh-CN': './assets/zh-CN/special_arena/END_COMPETITION.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'zh-CN': (584, 747, 626, 770)}, color={'zh-CN': (105, 192, 236)}, button={'zh-CN': (584, 747, 626, 770)}, file={'zh-CN': './assets/zh-CN/special_arena/FREE_OPPORTUNITY_CHECK.png'})
INTO_COMPETITION = Button(area={'zh-CN': (428, 1035, 552, 1067)}, color={'zh-CN': (125, 174, 216)}, button={'zh-CN': (428, 1035, 552, 1067)}, file={'zh-CN': './assets/zh-CN/special_arena/INTO_COMPETITION.png'})
NEXT_SEASON = Button(area={'zh-CN': (505, 589, 566, 601)}, color={'zh-CN': (49, 69, 103)}, button={'zh-CN': (505, 589, 566, 601)}, file={'zh-CN': './assets/zh-CN/special_arena/NEXT_SEASON.png'})
OWN_POWER_CHECK = Button(area={'zh-CN': (438, 358, 465, 384)}, color={'zh-CN': (63, 65, 63)}, button={'zh-CN': (438, 358, 465, 384)}, file={'zh-CN': './assets/zh-CN/special_arena/OWN_POWER_CHECK.png'})
POWER_CHECK = Button(area={'zh-CN': (351, 737, 377, 762)}, color={'zh-CN': (203, 204, 205)}, button={'zh-CN': (351, 737, 377, 762)}, file={'zh-CN': './assets/zh-CN/special_arena/POWER_CHECK.png'})
SKIP = Button(area={'zh-CN': (226, 1060, 276, 1077)}, color={'zh-CN': (148, 148, 148)}, button={'zh-CN': (226, 1060, 276, 1077)}, file={'zh-CN': './assets/zh-CN/special_arena/SKIP.png'})
UPDATE_LIST = Button(area={'zh-CN': (572, 684, 641, 701)}, color={'zh-CN': (180, 179, 179)}, button={'zh-CN': (572, 684, 641, 701)}, file={'zh-CN': './assets/zh-CN/special_arena/UPDATE_LIST.png'})
