from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

END_COMPETITION = Button(area={'cn': (45, 1194, 86, 1236)}, color={'cn': (117, 116, 117)}, button={'cn': (45, 1194, 86, 1236)}, file={'cn': './assets/cn/special_arena/END_COMPETITION.png'})
FREE_OPPORTUNITY_CHECK = Button(area={'cn': (584, 747, 626, 770)}, color={'cn': (105, 192, 236)}, button={'cn': (584, 747, 626, 770)}, file={'cn': './assets/cn/special_arena/FREE_OPPORTUNITY_CHECK.png'})
INTO_COMPETITION = Button(area={'cn': (428, 1035, 552, 1067)}, color={'cn': (125, 174, 216)}, button={'cn': (428, 1035, 552, 1067)}, file={'cn': './assets/cn/special_arena/INTO_COMPETITION.png'})
NEXT_SEASON = Button(area={'cn': (146, 588, 212, 603)}, color={'cn': (48, 55, 58)}, button={'cn': (146, 588, 212, 603)}, file={'cn': './assets/cn/special_arena/NEXT_SEASON.png'})
OWN_POWER_CHECK = Button(area={'cn': (438, 358, 465, 384)}, color={'cn': (63, 65, 63)}, button={'cn': (438, 358, 465, 384)}, file={'cn': './assets/cn/special_arena/OWN_POWER_CHECK.png'})
POWER_CHECK = Button(area={'cn': (351, 737, 377, 762)}, color={'cn': (203, 204, 205)}, button={'cn': (351, 737, 377, 762)}, file={'cn': './assets/cn/special_arena/POWER_CHECK.png'})
SKIP = Button(area={'cn': (226, 1060, 276, 1077)}, color={'cn': (148, 148, 148)}, button={'cn': (226, 1060, 276, 1077)}, file={'cn': './assets/cn/special_arena/SKIP.png'})
UPDATE_LIST = Button(area={'cn': (572, 684, 641, 701)}, color={'cn': (180, 179, 179)}, button={'cn': (572, 684, 641, 701)}, file={'cn': './assets/cn/special_arena/UPDATE_LIST.png'})