from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CHANGE = Button(area={'cn': (449, 202, 481, 232)}, color={'cn': (80, 81, 77)}, button={'cn': (449, 202, 481, 232)}, file={'cn': './assets/cn/mission_pass/CHANGE.png'})
COMPLETED_CHECK = Button(area={'cn': (659, 389, 673, 412)}, color={'cn': (239, 222, 220)}, button={'cn': (659, 389, 673, 412)}, file={'cn': './assets/cn/mission_pass/COMPLETED_CHECK.png'})
DOT = Button(area={'cn': (697, 169, 708, 183)}, color={'cn': (250, 126, 96)}, button={'cn': (697, 169, 708, 183)}, file={'cn': './assets/cn/mission_pass/DOT.png'})
EXPAND = Button(area={'cn': (451, 206, 480, 229)}, color={'cn': (90, 93, 90)}, button={'cn': (451, 206, 480, 229)}, file={'cn': './assets/cn/mission_pass/EXPAND.png'})
PASS_BANNER = Button(area={'cn': (579, 188, 709, 247)}, color={'cn': (133, 145, 159)}, button={'cn': (579, 188, 709, 247)}, file={'cn': './assets/cn/mission_pass/PASS_BANNER.png'})
PASS_CHECK = Button(area={'cn': (137, 330, 181, 364)}, color={'cn': (108, 115, 120)}, button={'cn': (137, 330, 181, 364)}, file={'cn': './assets/cn/mission_pass/PASS_CHECK.png'})
PASS_MISSION = Button(area={'cn': (489, 405, 563, 427)}, color={'cn': (207, 206, 209)}, button={'cn': (489, 405, 563, 427)}, file={'cn': './assets/cn/mission_pass/PASS_MISSION.png'})
PASS_NO_REWARD = Button(area={'cn': (317, 1180, 398, 1201)}, color={'cn': (154, 151, 152)}, button={'cn': (317, 1180, 398, 1201)}, file={'cn': './assets/cn/mission_pass/PASS_NO_REWARD.png'})
PASS_REWARD = Button(area={'cn': (158, 405, 235, 427)}, color={'cn': (201, 201, 204)}, button={'cn': (158, 405, 235, 427)}, file={'cn': './assets/cn/mission_pass/PASS_REWARD.png'})
RANK_UP_CHECK = Button(area={'cn': (289, 587, 430, 617)}, color={'cn': (89, 92, 89)}, button={'cn': (289, 587, 430, 617)}, file={'cn': './assets/cn/mission_pass/RANK_UP_CHECK.png'})
RECEIVE = Button(area={'cn': (318, 1182, 377, 1200)}, color={'cn': (155, 152, 152)}, button={'cn': (318, 1182, 377, 1200)}, file={'cn': './assets/cn/mission_pass/RECEIVE.png'})
