from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CHANGE = Button(area={'zh-CN': (449, 202, 481, 232)}, color={'zh-CN': (80, 81, 77)}, button={'zh-CN': (449, 202, 481, 232)}, file={'zh-CN': './assets/zh-CN/mission_pass/CHANGE.png'})
DOT = Button(area={'zh-CN': (697, 169, 708, 183)}, color={'zh-CN': (250, 126, 96)}, button={'zh-CN': (697, 169, 708, 183)}, file={'zh-CN': './assets/zh-CN/mission_pass/DOT.png'})
EXPAND = Button(area={'zh-CN': (451, 206, 480, 229)}, color={'zh-CN': (90, 93, 90)}, button={'zh-CN': (451, 206, 480, 229)}, file={'zh-CN': './assets/zh-CN/mission_pass/EXPAND.png'})
MISSION_RED_POINT = Button(area={'zh-CN': (668, 366, 682, 380)}, color={'zh-CN': (243, 148, 128)}, button={'zh-CN': (668, 366, 682, 380)}, file={'zh-CN': './assets/zh-CN/mission_pass/MISSION_RED_POINT.png'})
PASS_BANNER = Button(area={'zh-CN': (579, 188, 709, 247)}, color={'zh-CN': (133, 145, 159)}, button={'zh-CN': (579, 188, 709, 247)}, file={'zh-CN': './assets/zh-CN/mission_pass/PASS_BANNER.png'})
PASS_CHECK = Button(area={'zh-CN': (137, 330, 181, 364)}, color={'zh-CN': (108, 115, 120)}, button={'zh-CN': (137, 330, 181, 364)}, file={'zh-CN': './assets/zh-CN/mission_pass/PASS_CHECK.png'})
PASS_MISSION = Button(area={'zh-CN': (507, 382, 543, 402)}, color={'zh-CN': (168, 168, 168)}, button={'zh-CN': (507, 382, 543, 402)}, file={'zh-CN': './assets/zh-CN/mission_pass/PASS_MISSION.png'})
PASS_MISSION_2 = Button(area={'zh-CN': (504, 407, 543, 426)}, color={'zh-CN': (91, 91, 92)}, button={'zh-CN': (504, 407, 543, 426)}, file={'zh-CN': './assets/zh-CN/mission_pass/PASS_MISSION_2.png'})
PASS_REWARD = Button(area={'zh-CN': (176, 382, 216, 402)}, color={'zh-CN': (161, 161, 162)}, button={'zh-CN': (176, 382, 216, 402)}, file={'zh-CN': './assets/zh-CN/mission_pass/PASS_REWARD.png'})
PASS_REWARD_2 = Button(area={'zh-CN': (176, 406, 216, 426)}, color={'zh-CN': (94, 94, 95)}, button={'zh-CN': (176, 406, 216, 426)}, file={'zh-CN': './assets/zh-CN/mission_pass/PASS_REWARD_2.png'})
RANK_UP_CHECK = Button(area={'zh-CN': (289, 587, 430, 617)}, color={'zh-CN': (89, 92, 89)}, button={'zh-CN': (289, 587, 430, 617)}, file={'zh-CN': './assets/zh-CN/mission_pass/RANK_UP_CHECK.png'})
REWARD_RED_POINT = Button(area={'zh-CN': (341, 367, 353, 379)}, color={'zh-CN': (250, 125, 100)}, button={'zh-CN': (341, 367, 353, 379)}, file={'zh-CN': './assets/zh-CN/mission_pass/REWARD_RED_POINT.png'})
