from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

RECEIVE = Button(area={'zh-CN': (497, 1074, 592, 1096), 'en-US': (497, 1074, 592, 1096)}, color={'zh-CN': (137, 216, 251), 'en-US': (137, 216, 251)}, button={'zh-CN': (497, 1074, 592, 1096), 'en-US': (497, 1074, 592, 1096)}, file={'zh-CN': './assets/zh-CN/mailbox/RECEIVE.png', 'en-US': './assets/zh-CN/mailbox/RECEIVE.png'})
