from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

RECEIVE = Button(area={'zh-cn': (497, 1074, 592, 1096)}, color={'zh-cn': (137, 216, 251)}, button={'zh-cn': (497, 1074, 592, 1096)}, file={'zh-cn': './assets/zh-cn/mailbox/RECEIVE.png'})
