from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

RECEIVE = Button(area={'zh-CN': (497, 1074, 592, 1096), 'en-US': (494, 1076, 558, 1095)}, color={'zh-CN': (137, 216, 251), 'en-US': (111, 206, 248)}, button={'zh-CN': (497, 1074, 592, 1096), 'en-US': (494, 1076, 558, 1095)}, file={'zh-CN': './assets/zh-CN/mailbox/RECEIVE.png', 'en-US': './assets/en-US/mailbox/RECEIVE.png'})
