from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CHALLENGE_BATTLE = Button(area={'zh-CN': (490, 1172, 618, 1203)}, color={'zh-CN': (122, 173, 216)}, button={'zh-CN': (490, 1172, 618, 1203)}, file={'zh-CN': './assets/zh-CN/challenge/CHALLENGE_BATTLE.png'})
CHALLENGE_BATTLE_DONE = Button(area={'zh-CN': (489, 1172, 616, 1203)}, color={'zh-CN': (96, 97, 98)}, button={'zh-CN': (489, 1172, 616, 1203)}, file={'zh-CN': './assets/zh-CN/challenge/CHALLENGE_BATTLE_DONE.png'})
CHALLENGE_CANCEL = Button(area={'zh-CN': (692, 658, 713, 679)}, color={'zh-CN': (118, 120, 120)}, button={'zh-CN': (692, 658, 713, 679)}, file={'zh-CN': './assets/zh-CN/challenge/CHALLENGE_CANCEL.png'})
CHALLENGE_CHECK = Button(area={'zh-CN': (20, 37, 90, 56)}, color={'zh-CN': (127, 128, 127)}, button={'zh-CN': (20, 37, 90, 56)}, file={'zh-CN': './assets/zh-CN/challenge/CHALLENGE_CHECK.png'})
CHALLENGE_QUICKLY_DISABLE = Button(area={'zh-CN': (526, 1092, 611, 1111)}, color={'zh-CN': (123, 123, 123)}, button={'zh-CN': (526, 1092, 611, 1111)}, file={'zh-CN': './assets/zh-CN/challenge/CHALLENGE_QUICKLY_DISABLE.png'})
CHALLENGE_QUICKLY_ENABLE = Button(area={'zh-CN': (526, 1092, 609, 1111)}, color={'zh-CN': (252, 175, 141)}, button={'zh-CN': (526, 1092, 609, 1111)}, file={'zh-CN': './assets/zh-CN/challenge/CHALLENGE_QUICKLY_ENABLE.png'})
CHALLENGE_QUICK_TICKET = Button(area={'zh-CN': (333, 967, 359, 1003)}, color={'zh-CN': (113, 53, 53)}, button={'zh-CN': (333, 967, 359, 1003)}, file={'zh-CN': './assets/zh-CN/challenge/CHALLENGE_QUICK_TICKET.png'})
CHALLENGE_STAGE_CHECK = Button(area={'zh-CN': (112, 860, 205, 883)}, color={'zh-CN': (189, 189, 189)}, button={'zh-CN': (112, 860, 205, 883)}, file={'zh-CN': './assets/zh-CN/challenge/CHALLENGE_STAGE_CHECK.png'})
TEMPLATE_CHALLENGE_STAGE = Template(file={'zh-CN': './assets/zh-CN/challenge/TEMPLATE_CHALLENGE_STAGE.png'})
TEMPLATE_CLEAR_STAGE = Template(file={'zh-CN': './assets/zh-CN/challenge/TEMPLATE_CLEAR_STAGE.png'})
