from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COMPLETE = Button(area={'zh-CN': (329, 1167, 390, 1191), 'en-US': (329, 1167, 390, 1191)}, color={'zh-CN': (144, 145, 147), 'en-US': (144, 145, 147)}, button={'zh-CN': (329, 1167, 390, 1191), 'en-US': (329, 1167, 390, 1191)}, file={'zh-CN': './assets/zh-CN/episode_viewing/COMPLETE.png', 'en-US': './assets/zh-CN/episode_viewing/COMPLETE.png'})
INCOMPLETE = Button(area={'zh-CN': (543, 1173, 602, 1191), 'en-US': (543, 1173, 602, 1191)}, color={'zh-CN': (159, 156, 156), 'en-US': (159, 156, 156)}, button={'zh-CN': (543, 1173, 602, 1191), 'en-US': (543, 1173, 602, 1191)}, file={'zh-CN': './assets/zh-CN/episode_viewing/INCOMPLETE.png', 'en-US': './assets/zh-CN/episode_viewing/INCOMPLETE.png'})
REWARD = Button(area={'zh-CN': (534, 1172, 614, 1191), 'en-US': (534, 1172, 614, 1191)}, color={'zh-CN': (163, 224, 250), 'en-US': (163, 224, 250)}, button={'zh-CN': (534, 1172, 614, 1191), 'en-US': (534, 1172, 614, 1191)}, file={'zh-CN': './assets/zh-CN/episode_viewing/REWARD.png', 'en-US': './assets/zh-CN/episode_viewing/REWARD.png'})
TEMPLATE_EPISODE = Template(file={'zh-CN': './assets/zh-CN/episode_viewing/TEMPLATE_EPISODE.png', 'en-US': './assets/zh-CN/episode_viewing/TEMPLATE_EPISODE.png'})
